isc.ClassFactory.defineClass("App","VLayout").addClassProperties({appRootUrl:contextRoot,navDS:"MenuItem",userDataSource:"User",dsRequestUrl:contextRoot+"/SmartSource/loadDS.json",loginRequestUrl:contextRoot+"/j_spring_security_check",logoutRequestUrl:contextRoot+"/logout",userRequestUrl:contextRoot+"/user/loadUser.json",localeRequestUrl:contextRoot+"/Localization/loadLocale.json",hasRoleUrl:contextRoot+"/user/hasRole.json",userChangePwdUrl:contextRoot+"/user/updatePassword.json",smartFileDownloadUrl:contextRoot+
"/SmartFile/downloadFile",helpFileUrl:contextRoot+"/help/help.htm",locale:null,layoutProperties:{height:"100%",width:"99%"},getDataSource:function(a,c){var b;if(b=SmartDataSource.get(a))return c&&c(b),b;this.loadDataSource(a,function(a){c&&c(a);return b=a})},loadDataSource:function(a,c){console.log("loadDataSource("+a+")");this.dataRequest(this.dsRequestUrl,{ID:a},function(a,h,f){403==a.httpResponseCode?(isc.warn(a.httpResponseText),c&&c(null)):(a=isc.JSON.decode(h),0<a.response.data.length?App.registerDataSources(a.response.data,
function(a){c&&c(a)}):0==a.response.status&&c&&c(null))},!0,!1)},dataRequest:function(a,c,b,h,f,e){c||(c={});void 0==h&&(h=!1);void 0==f&&(f=!0);a=isc.addProperties({params:c,actionURL:a,willHandleError:h,sendNoQueue:!0,evalResult:f,callback:b},e);try{isc.RPCManager.sendRequest(a)}catch(d){return d}},_evalPropertyValue:function(a){var c=a;try{if(isA.String(a))if(-1<a.indexOf(":")&&0==a.indexOf("{")){var c=isc.JSON.decode(a),b;for(b in c)c.hasOwnProperty(b)&&(c[b]=App._evalPropertyValue(c[b]))}else 0==
a.indexOf("function")?c=eval("("+a+")"):-1!=a.indexOf("i18nMessages")&&(c=eval(a));else if(isA.Array(a))for(b=0;b<a.length;b++){var h=a[b];if(isA.Object(h))for(var f in h)h.hasOwnProperty(f)&&(h[f]=App._evalPropertyValue(h[f]));else h=App._evalPropertyValue(h);c[b]=h}}catch(e){c=a}return c},registerDataSources:function(a,c){var b=[],h=[],f;isc.isAn.Array(a)||(a=[a]);if(a)for(var e=0;e<a.length;e++){var d=a[e];d.customProfile&&(d.customProfile=isc.JSON.decode(d.customProfile));d.initValues&&(d.initValues=
isc.JSON.decode(d.initValues));for(var g in d)if(d.hasOwnProperty(g)&&"string"==typeof d[g]&&"gridProperties"!=g&&"formProperties"!=g)if("dsProperties"==g){var k=isc.JSON.decode(d.dsProperties),m;for(m in k)d[m]=App._evalPropertyValue(k[m])}else-1!=d[g].indexOf("i18nMessages")?d[g]=eval(d[g]):-1!=d[g].indexOf("function(")&&(d[g]=eval("("+d[g]+")"));if(d.fields)for(var l=0;l<d.fields.length;l++){0==d.fields[l].canSave&&(d.fields[l].canFocus=!1);d.fields[l].validators&&(d.fields[l].validators=App._evalPropertyValue(isc.JSON.decode(d.fields[l].validators)));
if(d.fields[l].formItemProps)for(m in d.fields[l].formItemProps=isc.JSON.decode(d.fields[l].formItemProps),k=d.fields[l].formItemProps,k)d.fields[l][m]=App._evalPropertyValue(k[m]);d.fields[l].valueMap&&(k=d.fields[l].valueMap,isA.String(k)&&(-1<k.indexOf(":")&&-1<k.indexOf("{")?d.fields[l].valueMap=App._evalPropertyValue(k):d.fields[l].valueMap=k.split(",")));for(g in d.fields[l])d.fields[l].hasOwnProperty(g)&&"string"==typeof d.fields[l][g]&&-1!=d.fields[l][g].indexOf("i18nMessages")&&(d.fields[l][g]=
eval(d.fields[l][g]))}if(d.operations&&isAn.Array(d.operations))for(var q=0;q<d.operations.length;q++){var p=d.operations[q];for(g in p)if(p.hasOwnProperty(g)&&"string"==typeof p[g]){if(-1!=p[g].indexOf("i18nMessages"))try{p[g]=eval(p[g])}catch(v){}"canPerform"==g&&-1!=p[g].indexOf("function")&&(p[g]=eval("("+p[g]+")"))}if(p.operationParams)for(var u in p.operationParams){var n=p.operationParams[u];if(n.formItemProps){k=isc.JSON.decode(n.formItemProps);for(m in k)n[m]=App._evalPropertyValue(k[m]);
delete n.formItemProps}k=n.valueMap;isA.String(k)&&(-1<k.indexOf(":")&&-1<k.indexOf("{")?n.valueMap=isc.JSON.decode(k):n.valueMap=k.split(","));if(n.optionDataSource){var k=n.optionDataSource,t=SmartDataSource.get(k);t||b.contains(k)||b.push(k)}for(g in n)n.hasOwnProperty(g)&&"string"==typeof n[g]&&(n[g]=App._evalPropertyValue(n[g]))}}f=SmartDataSource.create(d);f.setAccess();console.log(f);h.push(f);isc.ClassFactory.addGlobalID(f);App.dsMeta||(App.dsMeta={});App.dsMeta[f.id]=f.ID}for(e=0;e<h.length;e++){if(h[e].inheritsFrom){var r=
h[e].inheritsFrom;SmartDataSource.get(r)||b.contains(r)||b.push(r)}h[e].detailFormDS&&(d=h[e].detailFormDS,SmartDataSource.get(r)||b.contains(d)||b.push(d));if(h[e].fields)for(l in h[e].fields)d=h[e].fields[l],d.optionDataSource?(k=d.optionDataSource,(t=SmartDataSource.get(k))||b.contains(k)||b.push(k)):d.foreignKey&&-1<d.foreignKey.indexOf(".")&&(d=d.foreignKey.split(".")[0],SmartDataSource.get(d)||b.contains(d)||b.push(d))}if(0<b.length){for(h=0;h<b.length;h++)SmartDataSource.get(b[h])&&b.removeAt(h);
0<b.length?App.loadDataSource(b,function(a){c(f)}):c(f)}else c(f)},getHelp:function(){return isc.HelpLayout.create({homeTitle:isc.i18nMessages["smartsfs.buttons.obsah.label"],closeTitle:isc.i18nMessages["smartsfs.buttons.exit.label"],helpPath:App.helpFileUrl})},_findParentSmartClass:function(a,c){var b=a;try{for(;!b.isA(c);)try{b=b.parentElement}catch(h){break}}catch(h){console.log("undefined parentElement")}return void 0!=b&&b.isA(c)?b:null},_findParentTabSet:function(a){for(;!a.hasOwnProperty("tabSet");)try{a=
a.parentElement}catch(c){break}return a.hasOwnProperty("tabSet")?a.tabSet:null},_createExpandRecordComp:function(a,c,b,h,f,e,d){f=f||"normal";var g=d||{},k=DataSource.get(a.detailFormDS)||a;d||(d=k.getPrimaryKeyFieldName(),g[d]=c[d]);var m=function(){if(1!=this.detail.canEdit||null!=this._tabSet&&0!=this._tabSet.getSelectedTabNumber())if(this._tabSet)if(0==this._tabSet.getSelectedTabNumber()){var a=this.detail.items.find({canFocus:!0});this.detail.focusInItem(a)}else this._tabSet.getTabPane(this._tabSet.getSelectedTab()).focusInside();
else a=this.detail.items.find({canFocus:!0}),this.detail.focusInItem(a);else for(a=0;a<this.detail.items.length;a++)if(this.detail.items[a].hasOwnProperty("canEdit")&&0!=this.detail.items[a].canEdit){this.detail.focusInItem(this.detail.items[a]);break}};expandoDataSaved=function(a,d){!0===a&&b&&(b.collapseRecord(c),b.focusInRow(b.getFocusRow()));isA.Function(this.detail.dataSaved)&&this.detail.dataSaved(d)};a.detailFormDS?d=App._customCompDetail(a,k,{dataSource:k,initialValues:g,parentDataSource:a,
mode:"EDIT_BY_PK",brefField:e,brefValue:c[e],type:f,cancel:function(){b&&(b.collapseRecord(c),b.focusInRow(b.getFocusRow()))},height:h||b.getHeight()||350,_canSwitchLayout:!1,_ownerComp:b._ownerComp,focusInside:m,dataSaved:expandoDataSaved,padding:5})||DetailFormComponentAny.create({dataSource:k,initialValues:g,parentDataSource:a,mode:"EDIT_BY_PK",brefField:e,brefValue:c[e],type:f,cancel:function(){b&&(b.collapseRecord(c),b.focusInRow(b.getFocusRow()))},height:h||b.getHeight()||350,_canSwitchLayout:!1,
_ownerComp:b._ownerComp,focusInside:m,dataSaved:expandoDataSaved,padding:5}):(d=App._customCompDetail(a,k,{dataSource:k,type:f,initialValues:c,mode:"EDIT_RECORD",brefField:e,brefValue:c[e],type:f,cancel:function(){b&&(b.collapseRecord(c),b.focusInRow(b.getFocusRow()))},height:h||b.getHeight()||350,_canSwitchLayout:!1,_ownerComp:b._ownerComp,focusInside:m,dataSaved:expandoDataSaved,padding:5}),d||(a.detailFormUri?(g.brefField=e,g.brefValue=c[e],g.type=f,g.mode="EDIT_BY_PK",g.dataSource=k.ID,d=isc.HTMLPane.create({contentsURL:contextRoot+
a.detailFormUri,contentsURLParams:g,dataSource:k,cancel:function(){b&&(b.collapseRecord(c),b.focusInRow(b.getFocusRow()))},height:h||b.getHeight()||350,_canSwitchLayout:!1,_ownerComp:b._ownerComp,focusInside:m,dataSaved:expandoDataSaved,padding:5})):d=DetailFormComponentAny.create({dataSource:k,type:f,initialValues:c,mode:"EDIT_RECORD",brefField:e,brefValue:c[e],type:f,cancel:function(){b&&(b.collapseRecord(c),b.focusInRow(b.getFocusRow()))},height:h||b.getHeight()||350,_canSwitchLayout:!1,_ownerComp:b._ownerComp,
focusInside:m,dataSaved:expandoDataSaved,padding:5})));d.delayCall("focusInside");return d},_customCompDetail:function(a,c,b,h){a=a.detailFormUri;return c.isA("DataSource")?isA.Function(CustomComponents[a])?CustomComponents.invokeDetailCompMethod(a,b):null:(isc.logWarn("custom detail iba s nacitanym dataSource "+c),null)},_showDetailByPK:function(a,c,b,h,f,e,d,g){h=h||"normal";var k={},m={};if(!a.detailFormDS&&!1===a.canEdit&&g){var l=g.grid.getSelectedRecord(),q="_tabDetail_"+a.ID+"_"+c,m=App._customCompDetail(a,
a,{dataSource:a,type:h,initialValues:l,mode:"EDIT_RECORD",brefField:f,brefValue:e,type:h,tabSet:b,_myTabName:q,_ownerComp:d,_fromGridCom:g})||DetailFormComponentAny.create({dataSource:a,type:h,initialValues:l,mode:"EDIT_RECORD",brefField:f,brefValue:e,type:h,tabSet:b,_myTabName:q,_ownerComp:d,_fromGridCom:g}),l=m.dataSource.title+" ["+l[a.titleField]+"]";if(!b.getTab(q)){var p=b.getSelectedTabNumber();b.addTab({name:q,title:l,canClose:!0,pane:m},p+1)}b.selectTab(q)}else q=a.detailFormDS||a.ID,null!=
c&&void 0!=c&&App.getDataSource(q,function(l){l&&l.fetchRecord(c,function(n){if(n.data&&null!=n.data){var p=n.data[0];n=l.getPrimaryKeyFieldName();k[n]=c;n="_tabDetail_"+l.ID+"_"+c;a.detailFormDS?m=App._customCompDetail(a,l,{dataSource:l,initialValues:k,parentDataSource:a,mode:"EDIT_BY_PK",brefField:f,brefValue:e,type:h,tabSet:b,_myTabName:n,_ownerComp:d,_fromGridCom:g})||DetailFormComponentAny.create({dataSource:l,initialValues:k,parentDataSource:a,mode:"EDIT_BY_PK",brefField:f,brefValue:e,type:h,
tabSet:b,_myTabName:n,_ownerComp:d,_fromGridCom:g}):(m=App._customCompDetail(a,l,{dataSource:l,type:h,initialValues:p,mode:"EDIT_RECORD",brefField:f,brefValue:e,type:h,tabSet:b,_myTabName:n,_ownerComp:d,_fromGridCom:g}),m||(a.detailFormUri?-1<a.detailFormUri.indexOf("/")&&(k.brefField=f,k.brefValue=e,k.type=h,k.tabSet=b.ID,k.mode="EDIT_BY_PK",k.dataSource=l.ID,m=isc.HTMLPane.create({contentsURL:contextRoot+a.detailFormUri,contentsURLParams:k,dataSource:l,_myTabName:n,_ownerComp:d,_fromGridCom:g})):
m=DetailFormComponentAny.create({dataSource:l,type:h,initialValues:p,mode:"EDIT_RECORD",brefField:f,brefValue:e,type:h,tabSet:b,_myTabName:n,_ownerComp:d,_fromGridCom:g})));p=m.dataSource.title+" ["+p[a.titleField]+"]";if(!b.getTab(n)){var q=b.getSelectedTabNumber();b.addTab({name:n,title:p,canClose:!0,pane:m},q+1)}b.selectTab(n)}})})},_addRecord:function(a,c,b,h,f){var e=c;e&&void 0!=e||(e=a);var d={};a.brefField&&(d[a.brefField]=a.brefValue);h&&isc.addProperties(d,h);var g,k="_tabDetail_"+e.dataSource.ID+
"_new"+isc.timeStamp();e.dataSource.detailFormDS?App.getDataSource(e.dataSource.detailFormDS,function(b){b&&(k="_tabDetail_"+b.ID+"_new"+isc.timeStamp(),b.initValues&&isc.addProperties(d,b.initValues),g=App._customCompDetail(e.dataSource,b,{dataSource:b,initialValues:d,parentDataSource:e.dataSource,mode:"NEW",type:a.type,tabSet:f?f:a,_myTabName:k,_ownerComp:e._ownerComp,_fromGridCom:e})||DetailFormComponentAny.create({dataSource:b,initialValues:d,parentDataSource:e.dataSource,mode:"NEW",type:a.type,
tabSet:f?f:a,_myTabName:k,_ownerComp:a._ownerComp,_fromGridCom:e}))}):(g=App._customCompDetail(e.dataSource,e.dataSource,{dataSource:e.dataSource,type:a.type,initialValues:d,mode:"NEW",tabSet:f?f:a,_myTabName:k,_ownerComp:e._ownerComp,_fromGridCom:e}),g||(e.dataSource.detailFormUri?(d.type=O.type,d.tabSet=f?f.ID:O.tabSet.ID,d.mode="NEW",g=isc.HTMLPane.create({contentsURL:contextRoot+e.dataSource.detailFormUri,contentsURLParams:d,dataSource:e.dataSource,_myTabName:k,_ownerComp:e._ownerComp,_fromGridCom:e})):
(e.dataSource.initValues&&isc.addProperties(d,e.dataSource.initValues),g=DetailFormComponentAny.create({dataSource:e.dataSource,initialValues:d,mode:"NEW",type:a.type,tabSet:f?f:a,_myTabName:k,_ownerComp:e._ownerComp,_fromGridCom:e}))));if(b){var m;a.isA("GridComponentAny")&&(m=a.grid.getSelectedRecord());a.isA("DetailComponentTemplate")&&(m=a.detail.valuesManager.getValues());m&&(g.detail.valuesManager.setValues(m),c=g.detail.valuesManager.getValues(),c.id=null,c.createdBy=null,c.dateCreated=null,
c.updatedBy=null,c.lastUpdated=null,c.version=null,g.detail.valuesManager.setValues(c))}c=a;if(f?f:c!=c)c=f;b=c.getSelectedTabNumber();a.isA("DetailComponentTemplate")?(g.tabSet=a.tabSet,c.tabSet.addTab({name:k,title:g.dataSource.title+" ["+isc.i18nMessages["default.new.label"].messageArgs("")+"]",canClose:!0,pane:g},b+1),c.tabSet.selectTab(k)):(c.addTab({name:k,title:g.dataSource.title+" ["+isc.i18nMessages["default.new.label"].messageArgs("")+"]",canClose:!0,pane:g},b+1),c.selectTab(k))},_convertObjToArray:function(a){if(isA.Array(a))return a;
for(var c=[],b=0;b<Object.keys(a).length;b++)Object.keys(a),c.add(a[Object.keys(a)[b]]);return c}}).addProperties({height:"99%",width:"100%",splitPane:null,keyDown:function(){switch(isc.Event.getKey()){case "f10":return App.get.splitPane.navigationPane.focus(),!1;case "f5":return!1}},initWidget:function(){this.Super("initWidget",arguments);App.get=this},loadUser:function(a,c,b,h){var f=this;Lokalizacia.setLocale(f.locale,function(e,d){var g=f.config["smartsfs.security.useOTP"].toString().toBoolean();
f.locale=e;void 0==a||null==a?(a={},void 0!==d&&null!=d&&d.hasOwnProperty("enabled")&&1==d.enabled&&(f.user=SmartUser.create(d))):(a.j_username=a.username,a.j_password=a.password,b&&!d&&(f.user=void 0));void 0!=f.user&&f.user.enabled?(document.title=isc.i18nMessages["default.application.title"],c&&c(!0),g&&f.user.hasAnyRole("ROLE_PRE_AUTH")?isc.showOTPDialog(f.user.firstOTPLogin,b,h):1!=b?f.createAppLayout():h&&h()):(a.ajax=!0,App.dataRequest(App.loginRequestUrl,a,function(d,e,l){e&&(e.success?App.dataRequest(App.userRequestUrl,
{username:e.username},function(a,d){f.user=SmartUser.create(d.response.data);Lokalizacia.setLocale(f.user.lang,function(a){f.locale=a;document.title=isc.i18nMessages["default.application.title"];c&&c(!0);g?isc.showOTPDialog(d.response.data.firstOTPLogin.toString().toBoolean(),b,h):1!=b?f.createAppLayout():h&&h()})}):e.error==isc.i18nMessages["springSecurity.errors.login.passwordExpired"]?isc.warn(isc.i18nMessages["springSecurity.errors.login.passwordExpired"],function(){c&&c(!0);SmartUser.changePasswordDialog({canClose:!1,
expired:!0,expiredUser:a.j_username})}):c?c(!1,e.error):f.loginUser(b,h))},!0))})},loginUser:function(a,c){var b={formFields:isc.LoginDialog.getPrototype().formDefaultFields};a&&(b.usernameItemProperties={disabled:!0});b=isc.showLoginDialog(function(b,f){App.get.loadUser(b,f,a,c)},b);b.observe(App.get,"userLoginSucces","observer.destroy()");a&&(b.loginForm.getItem("usernameItem").setValue(App.get.user.username),b.loginForm.getItem("passwordItem").focusInItem())},userLoginSucces:function(){console.log("user logged in")},
logoutUser:function(){var a=window.location.origin;a||(a=window.location.protocol+"//"+window.location.hostname+(window.location.port?":"+window.location.port:""));a+=App.logoutRequestUrl;window.location.href=a},createLoginMenu:function(){var a=App.get.config["smartsfs.changePassword.supported"].toString().toBoolean(),c=[];c.push({title:isc.i18nMessages["springSecurity.logout.button"],click:function(){App.get.logoutUser()}});(a||App.get.user.hasAnyRole("ROLE_SUPER"))&&c.push({title:isc.i18nMessages["springSecurity.expired.header"],
click:function(){SmartUser.changePasswordDialog({})}});c.push({title:isc.i18nMessages["user.myaccount.title"],click:function(){App.getDataSource(App.userDataSource,function(a){App._showDetailByPK(a,App.get.user.id,SmartTabSet.getById("appTabSet"))})}});return isc.Menu.create({showIcons:!1,defaultWidth:100,data:c})},createNavPane:function(a){App.getDataSource(App.navDS,function(c){c&&(c=isc.TreeGrid.create({dataSource:c,autoFetchData:!0,loadDataOnDemand:!1,showHeader:!1,showDropIcons:!1,canSort:!1,
sortField:"position",dataProperties:{openProperty:"isOpen"},nodeClick:function(a,c,f){if(c.isFolder)this.toggleFolder(c);else{var e="_tabGrid_"+c.id;appTabSet.getTab(e)?appTabSet.selectTab(e):c.uri?(a={type:"normal"},a.tabSet=appTabSet.ID,a.dataSource=c.gridDS,a=isc.HTMLPane.create({contentsURL:contextRoot+c.uri,contentsURLParams:a,autoDraw:!0,_myTabName:e}),appTabSet.addTab({title:c.title,canClose:!0,name:e,pane:a}),appTabSet.selectTab(e),App.get.splitPane.showDetailPane()):c.customCompFn?CustomComponents.invokeCompMethod(c.customCompFn,
appTabSet,"normal",c.gridDS,function(a,b){a&&(a._myTabName=e,appTabSet.addTab({title:b.pluralTitle,canClose:!0,name:e,pane:a}),appTabSet.selectTab(e),App.get.splitPane.showDetailPane())}):c.gridDS&&App.getDataSource(c.gridDS,function(a){if(a){var b=GridComponentAny.create({dataSource:a,tabSet:appTabSet,_myTabName:e,type:"normal"});appTabSet.addTab({title:a.pluralTitle,canClose:!0,name:e,pane:b});appTabSet.selectTab(e)}App.get.splitPane.showDetailPane()})}}}),a(c))})},createHomePane:function(){return isc.HTMLPane.create({contentsURL:App.appRootUrl+
"/home"})},createAppLayout:function(){console.log(App.get.user);App.get.userLoginSucces();App.userDataSource=App.get.config["smartsfs.datasources.user"]||App.userDataSource;App.navDS=App.get.config["smartsfs.datasources.menu"]||App.navDS;App.getDataSource("SmartSource");App.get.config["smartsfs.userSetting.supported"].toString().toBoolean()&&App.getDataSource("SmartUserSettings");var a=[];this.splitPane=isc.SplitPane.create({autoDraw:!1,navigationTitle:isc.i18nMessages["default.application.title"],
showLeftButton:!1,showRightButton:!0,paneChanged:function(a){isc.Browser.isHandset&&("detail"==a?this.navigationBar.rightButton.hide():this.navigationBar.rightButton.show())}});var c=App.get.createLoginMenu();this.splitPane.setDetailToolButtons([isc.Label.create({contents:isc.i18nMessages["springSecurity.logged.label"],wrap:!1,padding:5}),isc.MenuButton.create({title:" <b>"+App.get.user.titlename+"</b>",menu:c,autoFit:!0})]);"function"==typeof App.getHelp&&App.helpFileUrl&&(c=isc.BtnIcon.create({icon:"[SKIN]/custom/help.png",
title:"Help",prompt:isc.i18nMessages["smartsfs.buttons.help.label"],minWidth:24,margin:15,click:function(){null==this.fillScreenWindow&&(this.fillScreenWindow=isc.HelpWindow.create({title:isc.i18nMessages["smartsfs.buttons.help.label"]}),this.fillScreenWindow.addMember(App.getHelp()));this.fillScreenWindow.show();this.fillScreenWindow.bringToFront();this.fillScreenWindow.focus()}}),this.splitPane.detailToolButtons.push(c));var b=isc.SmartTabSet.create({ID:"appTabSet",tabBarPosition:"top",autoDraw:!1,
canCloseTabs:!0,destroyPanes:!0});App.get.createNavPane(function(c){App.get.splitPane.setNavigationPane(c);isc.Browser.isHandset&&App.get.splitPane.navigationBar.rightButton.addProperties({click:function(){App.get.splitPane.showDetailPane()},icon:"[SKIN]/NavigationBar/back_arrow~2_rtl.png"});App.get.splitPane.setDetailPane(b);isc.Browser.isHandset&&isc.Page.updateViewport(1,null,null,!0);isc.Browser.isHandset||a.push(Header.create());a.push(App.get.splitPane);isc.Browser.isHandset||a.push(Foother.create());
appTabSet.addTab({title:isc.i18nMessages["default.home.label"],canClose:!1,icon:"[SKIN]/custom/house.png",pane:App.get.createHomePane()});App.get.splitPane.showNavigationPane();App.get.setMembers(a);App.get.draw()})}});isc.ClassFactory.defineClass("Header","HLayout").addProperties({height:37,width:"100%",overflow:"hiden",leaveScrollbarGap:!1,disabled:!0,members:[isc.HTMLPane.create({overflow:"hidden",contents:function(){return App.get.config["smartsfs.header.contents"]}})]});
isc.ClassFactory.defineClass("Foother","HLayout").addProperties({height:15,width:"100%",overflow:"hiden",disabled:!0,members:[isc.HTMLPane.create({overflow:"hidden",contents:function(){return App.get.config["smartsfs.foother.contents"]}})]});
isc.ClassFactory.defineClass("HelpWindow","Window").addProperties({ID:"helpWindow",placement:"nearOrigin",canDragResize:!0,redrawOnResize:!0,keepInParentRect:!0,canFocus:!0,showMinimizeButton:!0,showMaximizeButton:!0,animateMinimize:!0,bodyColor:"#829CC0",width:"35%",height:"92%",right:0,left:"65%",top:"8%",headerIconDefaults:{src:"[SKIN]/custom/help.png",width:16,height:16},keyDown:function(){var a=isc.EventHandler.getKey();("Q"==a&&isc.EventHandler.ctrlKeyDown()||"Escape"==a)&&this.close()},initWidget:function(){this.Super("initWidget",
arguments);isc.Browser.isHandset&&(this.setWidth("100%"),this.placement="fillScreen")}});
isc.ClassFactory.defineClass("HelpLayout","VLayout").addProperties({width:"100%",height:"99%",homeTitle:"Obsah",closeTitle:"Zatvori\u0165",helpPath:contextRoot+"/help/help.htm",btbHome:function(){var a=this;return isc.IButton.create({title:a.homeTitle,autoFit:!0,icon:"[SKIN]/custom/house.png",showIcon:!0,click:function(){hlpPane.setContentsURL(a.helpPath);this.topElement.focus()}})},btnExit:function(){return isc.IButton.create({title:this.closeTitle,autoFit:!0,icon:"[SKIN]/custom/cancel.png",showIcon:!0,
click:function(){this.topElement.close()}})},hlpStack:function(){var a=this;return isc.HStack.create({height:30,layoutMargin:10,membersMargin:10,membersWidth:300,showEdges:!0,initWidget:function(){this.Super("initWidget",arguments);this.addMember(a.btbHome());this.addMember(a.btnExit())}})},hlpPage:function(){return isc.HTMLPane.create({ID:"hlpPane",showEdges:!1,canFocus:!1,backgroundColor:"white",contentsURL:this.helpPath,contentsType:"page"})},initWidget:function(){this.Super("initWidget",arguments);
this.addMember(this.hlpStack());this.addMember(this.hlpPage())}});
