isc.ClassFactory.defineClass("BtnIcon","IconButton").addProperties({showIcon:!0,showButtonTitle:!1,iconWidth:30,iconHeight:30});
isc.ClassFactory.defineClass("advFilt","BtnIcon").addProperties({title:"Advanced Filter",icon:"[SKIN]/actions/search.png",minWidth:24,dataComp:null,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.toggleFilter.prompt"]},click:function(){this.dataComp.advFilter.isVisible()?(this.dataComp.advFilter.clearCriteria(),this.dataComp.advFilter.hide(),this.dataComp.getMember(1).getMember(1).hide(),this.dataComp.getMember(1).getMember(2).show(),this.dataComp.grid.setShowFilterEditor(!0)):
(this.dataComp.advFilter.show(),this.dataComp.getMember(1).getMember(1).show(),this.dataComp.getMember(1).getMember(2).hide(),this.dataComp.grid.setShowFilterEditor(!1),this.dataComp.grid.setFilterEditorCriteria(null))}});
isc.ClassFactory.defineClass("advFiltRun","BtnIcon").addProperties({title:"Advanced Filter",prompt:"Advanced Filtruj",icon:"[SKIN]/actions/filter.png",minWidth:24,dataComp:null,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.doFilter.prompt"]},click:function(){this.dataComp.advFilter.isVisible()&&this.dataComp.grid.filterData(this.dataComp.advFilter.getCriteria())}});
isc.ClassFactory.defineClass("btnFilter","BtnIcon").addProperties({title:"Filter",prompt:"Filtruj",icon:"[SKIN]/actions/filter.png",minWidth:24,dataComp:null,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.doFilter.prompt"]},click:function(){this.dataComp.grid.filterData(this.dataComp.grid.getFilterEditorCriteria())}});
isc.ClassFactory.defineClass("btnRel","BtnIcon").addProperties({id:"btnRel",title:"Reload",prompt:"Reload",icon:"[SKIN]/actions/refresh.png",minWidth:24,dataComp:null,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.reload.prompt"]},click:function(){this.dataComp.invalidateCache()}});
isc.ClassFactory.defineClass("clrFilt","BtnIcon").addProperties({id:"clrFilt",title:"Clear Filter",icon:"[SKIN]/custom/clear_filter.png",minWidth:24,dataComp:null,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.clearFilter.prompt"]},click:function(){this.dataComp.hasOwnProperty("advFilter")&&this.dataComp.advFilter.clearCriteria();this.dataComp.grid.setFilterEditorCriteria(null);this.dataComp.grid.filterData()}});
isc.ClassFactory.defineClass("btnDetail","BtnIcon").addProperties({id:"btnDetail",title:"Detail",prompt:"Detail",icon:"[SKIN]/actions/view.png",minWidth:24,dataComp:null,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.showdetail.prompt"]},click:function(){this.dataComp.parentElement.mode="detail";this.dataComp.parentElement.getDetail(!1)}});
isc.ClassFactory.defineClass("btnCancel","BtnIcon").addProperties({id:"btnCancel",title:"Cancel",prompt:"Cancel",name:"cancel",icon:"[SKIN]/custom/cancel.png",minWidth:24,dataComp:null,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.cancel.prompt"]},click:function(){this.dataComp.cancel()}});
isc.ClassFactory.defineClass("btnSave","BtnIcon").addProperties({id:"btnSave",title:"Save",prompt:"Save",name:"save",disabled:!0,icon:"[SKIN]/custom/save.png",minWidth:24,dataComp:null,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.save.prompt"]},click:function(){this.dataComp.save()}});
isc.ClassFactory.defineClass("btnAdd","BtnIcon").addProperties({id:"btnAdd",title:"Add",name:"add",icon:"[SKIN]/actions/add.png",minWidth:24,dataComp:null,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.create.prompt"].messageArgs("")},click:function(){this.dataComp.getDetail(!0)}});
isc.ClassFactory.defineClass("btnRem","BtnIcon").addProperties({id:"btnRem",title:"Remove",prompt:"Remove",name:"remove",icon:"[SKIN]/actions/remove.png",minWidth:24,dataComp:null,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.remove.prompt"].messageArgs("")},click:function(){this.dataComp.remove()}});
isc.ClassFactory.defineClass("btnEdit","BtnIcon").addProperties({id:"btnEdit",title:"Edit",prompt:"Edit",name:"edit",icon:"[SKIN]/actions/edit.png",minWidth:24,showDisabledIcon:!0,dataComp:null,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.edit.prompt"].messageArgs("")},click:function(){this.dataComp.edit()}});
isc.ClassFactory.defineClass("btnAccept","BtnIcon").addProperties({id:"btnAccept",title:"Accept",prompt:"Accept",name:"accept",disabled:!0,icon:"[SKIN]/custom/ok.png",minWidth:24,dataComp:null,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.accept.prompt"].messageArgs("")},click:function(){this.dataComp.accept()}});
isc.ClassFactory.defineClass("btnDetailRel","BtnIcon").addProperties({id:"btnDetailRel",title:"Reload",prompt:"Reload",name:"reload",icon:"[SKIN]/actions/refresh.png",minWidth:24,dataComp:null,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.reload.prompt"]},click:function(){this.dataComp.reload()}});
isc.ClassFactory.defineClass("btnShowFilter","BtnIcon").addProperties({title:"Set filter",prompt:"Show filter",icon:"[SKIN]/custom/setfilter_Disabled.png",dataComp:null,minWidth:24,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.showfilter.prompt"]},click:function(){this.dataComp.grid.showFilterEditor?(this.setIcon("[SKIN]/custom/setfilter_Disabled.png"),this.dataComp.showFilter("Disabled")):(this.setIcon("[SKIN]/custom/setfilter.png"),this.dataComp.showFilter("Enabled"))}});
isc.ClassFactory.defineClass("btnCloneRec","BtnIcon").addProperties({id:"btnDetailRel",title:"Clone record",prompt:"Clone record",name:"copyrec",icon:"[SKIN]/custom/copy_paste.png",minWidth:24,dataComp:null,initWidget:function(){this.Super("initWidget",arguments);this.prompt=isc.i18nMessages["smartsfs.buttons.cloneec.prompt"]},click:function(){this.dataComp.clone()}});
isc.ClassFactory.defineClass("btnUserSetting","HLayout").addProperties({dataComp:null,usCriteria:null,usFilter:function(){return{_constructor:"AdvancedCriteria",operator:"and",criteria:[{fieldName:"name",operator:"notNull"},{fieldName:"appCase",operator:"equals",value:"grid"},{fieldName:"appObject",operator:"equals",value:this.dataComp.dataSource.name}]}},sysFilter:function(){return{_constructor:"AdvancedCriteria",operator:"and",criteria:[{fieldName:"name",operator:"isNull"},{fieldName:"appObject",
operator:"equals",value:this.dataComp.dataSource.name}]}},getUSDefData:function(a){App.getDataSource("SmartUserSettings",function(a){a.fetchData(this.sysFilter(),function(a){if(0<a.data.length)for(var e=0;e<a.data.length;e++);})})},getUSCriteria:function(){return this.usCriteria},initWidget:function(){this.Super("initWidget",arguments);var a=this;this.usdf=isc.DynamicForm.create({_handleSize:function(){if(500<App.get.splitPane.detailToolStrip.getVisibleWidth()-12)this.getField("name").setWidth(150),
this.setWidth(209),a.setWidth(257);else if(a.dataComp.toolBar&&0<a.dataComp.toolBar.members.length&&a.dataComp.toolBar.members[0].memberSizes){var c=App.get.splitPane.detailToolStrip.getVisibleWidth()-12,b=0,b=a.dataComp.toolBar.getVisibleWidth();b>c&&(c=b-c,0<c&&(this.getField("name").setWidth(this.getField("name").getVisibleWidth()-c),this.setWidth(this.getVisibleWidth()-c),a.setWidth(a.getVisibleWidth()-c)))}},initialCriteria:this.usFilter(),usssave:function(){var c=this.getField("name").getValue();
if(c&&"0"!=c||App.get.user.hasAnyRole("ROLE_SUPER")){var b=this.getField("name").getSelectedRecord();App.getDataSource("SmartUserSettings",function(e){var d=[{fields:a.dataComp.grid.fields}];d.push({groupByField:a.dataComp.grid.groupByField});d.push({currentGroupState:a.dataComp.grid.currentGroupState});d.push({sortFieldNum:a.dataComp.grid.sortFieldNum});d.push({sortField:a.dataComp.grid.sortField});d.push({sortDirection:a.dataComp.grid.sortDirection});d.push({showGridSummary:a.dataComp.grid.showGridSummary});
d.push({showGroupSummary:a.dataComp.grid.showGroupSummary});d.push({initialCriteria:a.dataComp.grid.initialCriteria});d.push({visibleAdvFilter:a.dataComp.advFilter.isVisible()});var g=isc.JSON.encode(d,{prettyPrint:!1}),f={};b||!c?c?(f={id:b.id,useDefault:!1,settingObject:g},e.updateData(f,function(a,d,c){e.updateCaches({operationType:"update",data:isA.Array(d)?d:[d]});isc.say(isc.i18nMessages["smartsfs.userSetting.saved"].messageArgs(b?b.name:f.name))})):App.getDataSource("SmartUserSettings",function(d){d.fetchData(a.sysFilter(),
function(c){if(0<c.data.length)for(var h=0;h<c.data.length;h++)b=c.data[h],f={id:b.id,useDefault:!1,settingObject:g},d.updateData(f,function(a,d,c){e.updateCaches({operationType:"update",data:isA.Array(d)?d:[d]});isc.say(isc.i18nMessages["smartsfs.userSetting.saved"].messageArgs(b?b.name:f.name))});else f={appCase:"grid",appObject:a.dataComp.dataSource.ID,name:"",user:App.get.user.id,useDefault:!1,settingObject:g},e.addData(f,function(d,c,g){e.updateCaches({operationType:"add",data:isA.Array(c)?c:
[c]});a.usdf.getField("name").fetchData();isc.say(isc.i18nMessages["smartsfs.userSetting.saved"].messageArgs(b?b.name:f.name))})})}):(c||(c=""),f={appCase:"grid",appObject:a.dataComp.dataSource.ID,name:c,user:App.get.user.id,useDefault:!1,settingObject:g},e.addData(f,function(d,c,g){e.updateCaches({operationType:"add",data:isA.Array(c)?c:[c]});a.usdf.getField("name").fetchData();isc.say(isc.i18nMessages["smartsfs.userSetting.saved"].messageArgs(b?b.name:f.name))}))})}},usremove:function(){var c=this.getField("name").getValue();
if(c&&"0"!=c||App.get.user.hasAnyRole("ROLE_SUPER")){var b=this.getField("name").getSelectedRecord();if(!c||b)if(c){var e={id:b.id};App.getDataSource("SmartUserSettings",function(d){d.removeData(e,function(c,b,e){d.updateCaches({operationType:"remove",data:isA.Array(b)?b:[b]});d.fetchData(a.usFilter,function(){a.usdf.getField("name").setValue(0);a.usdf.setDefault(!0)})})})}else App.getDataSource("SmartUserSettings",function(d){d.fetchData(a.sysFilter(),function(c){if(0<c.data.length)for(var f=0;f<
c.data.length;f++)b=c.data[f],e=e={id:b.id},d.removeData(e,function(c,b,e){d.updateCaches({operationType:"remove",data:isA.Array(b)?b:[b]});d.fetchData(a.usFilter,function(){a.usdf.getField("name").setValue(0);a.usdf.setDefault(!0)})})})})}},setDefault:function(c){App.getDataSource("SmartUserSettings",function(b){b.fetchData(a.sysFilter(),function(b){if(0<b.data.length){for(var d=0;d<b.data.length;d++)if(a.dataComp.grid.clearCriteria(),a.dataComp.advFilter.clearCriteria(),b.data[d].id){for(var g=
[],g=isc.JSON.decode(b.data[d].settingObject),f=0;f<g.length;f++)for(var k in g[f])a.dataComp.grid.setProperty(k,g[f][k]);a.dataComp.grid.initialCriteria=DataSource.combineCriteria(a.dataComp._requiredProfile,a.dataComp.remReqProfileFromCrit(a.dataComp.grid.initialCriteria));a.usCriteria=a.dataComp.grid.initialCriteria}a.usdf.reload();a.dataComp.grid.markForRedraw("sysUSS")}else!0===c&&(0!=a.dataComp.canFilter&&a.dataComp.grid.setShowFilterEditor(!1),a.dataComp.grid.setDataSource(a.dataComp.dataSource),
0!=a.dataComp.canFilter&&a.dataComp.grid.setShowFilterEditor(!0),a.usCriteria=null,a.dataComp.clearFilter(),a.dataComp.grid.markForRedraw("defaultUSS"))})})},reload:function(){a.dataComp.grid.setGroupByFieldSummaries(a.dataComp.grid.groupByField);a.dataComp.grid.setGroupState(a.dataComp.grid.currentGroupState);a.dataComp.grid.sortField?a.dataComp.grid.setSort({property:a.dataComp.grid.sortField,direction:a.dataComp.grid.sortDirection}):a.dataComp.grid.setSortState(null);a.dataComp.grid.visibleAdvFilter?
(a.dataComp.advFilter.show(),a.dataComp.toolBar._btnAdvFilter.show(),a.dataComp.toolBar._btnFilter.hide(),a.dataComp.grid.setShowFilterEditor(!1),a.dataComp.advFilter.setCriteria(a.dataComp.grid.initialCriteria?a.dataComp.grid.initialCriteria:null),a.dataComp.doFilter("advanced")):(a.dataComp.advFilter.hide(),a.dataComp.toolBar._btnAdvFilter.hide(),a.dataComp.toolBar._btnFilter.show(),a.dataComp.grid.setShowFilterEditor(!0),a.dataComp.grid.setCriteria(a.dataComp.grid.initialCriteria?a.dataComp.grid.initialCriteria:
null));a.dataComp.reload()},fields:[{name:"name",title:isc.i18nMessages["smartsfs.userSetting.buttons.label"],prompt:isc.i18nMessages["smartsfs.userSetting.buttons.prompt"],editorType:"comboBox",valueField:"id",displayField:"name",width:182,optionDataSource:"SmartUserSettings",pickListCriteria:this.usFilter(),addUnknownValues:!0,allowEmptyValue:!0,specialValues:{0:""},pickListProperties:{showHeader:!1,showCellContextMenus:!0},pickListFields:[{name:"id",hidden:!0},{name:"name"},{name:"settingObject",
hidden:!0}],changed:function(c,b,e){if(b.getSelectedRecord()){a.dataComp.grid.clearCriteria();a.dataComp.advFilter.clearCriteria();if("0"!=e){if(b.getSelectedRecord().id){e=[];e=isc.JSON.decode(b.getSelectedRecord().settingObject);for(b=0;b<e.length;b++)for(var d in e[b])a.dataComp.grid.setProperty(d,e[b][d]);a.dataComp.grid.initialCriteria=DataSource.combineCriteria(a.dataComp._requiredProfile,a.dataComp.remReqProfileFromCrit(a.dataComp.grid.initialCriteria));a.usCriteria=a.dataComp.grid.initialCriteria}}else a.usdf.setDefault(!0);
c.reload()}},icons:[{src:"[SKIN]/custom/save.png",name:"usave",prompt:isc.i18nMessages["smartsfs.buttons.save.prompt"],click:function(){a.usdf.usssave()}},{src:"[SKIN]/actions/remove.png",name:"uremove",prompt:isc.i18nMessages["smartsfs.buttons.remove.prompt"].messageArgs(""),click:function(){a.usdf.usremove()}}]}],initWidget:function(){this.Super("initWidget",arguments)}});this.addMember(this.usdf)}});
