ClassFactory.defineClass("SmartCalendarTemplate","SmartTabSet").addClassProperties({dateIsWorkDaySK:function(a,b){var c=a.getFullYear(),d=a.getMonth(),e=a.getDate(),d=d+","+e,f=(c%19*19+24)%30,k=(5+c%4*2+c%7*4+6*f)%7,e=22+f+k,f=f+k-9,c=31>=e?DateUtil.createLogicalDate(c,2,e):25<f?DateUtil.createLogicalDate(c,3,f-7):DateUtil.createLogicalDate(c,3,f),e=new Date(c);e.setDate(c.getDate()-2);f=new Date(c);f.setDate(c.getDate()+1);return"0,1 0,6 4,1 4,8 6,5 7,29 8,1 8,15 10,1 10,17 11,24 11,25 11,26".split(" ").contains(d)||
0==DateUtil.compareLogicalDates(e,a)||0==DateUtil.compareLogicalDates(f,a)||0==a.getDay()||6==a.getDay()?!1:!0}}).addProperties({height:"100%",width:"100%",overflow:"hidden",dataSource:null,parentDataSource:null,type:"normal",mode:"",tabSet:null,_myTabName:null,_detailCanvas:null,_calendar:null,keyDown:function(){var a=isc.EventHandler.getKey(),b=!0;("Q"==a&&isc.EventHandler.ctrlKeyDown()||"Escape"==a)&&this.cancel(function(a,d){b=!a});if("F"==a&&isc.EventHandler.ctrlKeyDown()||"f4"==a)this.doFilter(),
b=!1;if("R"==a&&isc.EventHandler.ctrlKeyDown()||"f5"==a)this.reload(),b=!1;return b},_customCalProps:function(){this._addCalProps={};if(null!=this.dataSource.formProperties){var a=isA.String(this.dataSource.formProperties)?isc.JSON.decode(this.dataSource.formProperties):this.dataSource.formProperties,b;for(b in a)this._addCalProps[b]=App._evalPropertyValue(a[b])}},_createCalendar:function(){var a=this;if(isA.emptyObject(a._addCalProps))a._addCalProps.eventDialogFields=[];else if(a._addCalProps.hasOwnProperty("eventDialogFields")){for(var b=
[],c=0;c<a._addCalProps.eventDialogFields.length;c++){var d=isc.addProperties({},a.dataSource.getField(a._addCalProps.eventDialogFields[c].name));b.add(d)}a._addCalProps.eventDialogFields=b}else a._addCalProps.eventDialogFields=[];a._addCalProps.eventDialogFields.addAt({name:"name",required:!0},0);a._addCalProps.eventDialogFields.add({name:"details",type:"button",click:function(b,c){var d=b.calendar,l=d.eventDialog.isNewEvent,h=d.eventDialog.event||{},g=d.eventDialog.currentStart,m=d.eventDialog.currentEnd,
n=b.getValues();l?a.addRecord(n):(l=isc.addProperties({},b.getCustomValues()),b.validate()&&(d._fromEventDialog=!0,g=d.createEventObject(h,g,m,null,null,b.getValue(d.nameField)),g=d.getCleanEventRecord(isc.addProperties({},g,l)),a.dataSource.updateData(g,function(b,c,e){d.processSaveResponse(b,c,e,h);a.getDetail(h)},{oldValues:h,componentId:this.ID,willHandleError:!0})))}});a._calendar=isc.Calendar.create(isc.addProperties({},{dataSource:a.dataSource,currentViewName:"day",autoFetchData:!0,timeFormatter:"toShortPadded24HourTime",
addEventButtonProperties:{click:function(){a.addRecord()}},keyDown:function(){return a.keyDown()},dateIsWorkday:SmartCalendarTemplate.dateIsWorkDaySK,shouldDisableDate:function(a,b){return this.showWorkday&&!this.dateIsWorkday(a)},eventClick:function(b,c){return"month"==c?(a.getDetail(b),!1):!0}},a._addCalProps));a._calendar.controlsBar.addMember(a._btnAdvFilter);a._calendar.controlsBar.addMember(a._btnClearFilter);a._btnReload=btnRel.create({dataComp:a}).addProperties({click:function(){this.dataComp.reload()}});
a._calendar.controlsBar.addMember(a._btnReload);return a._calendar},_createFilter:function(){var a=this;a._advFilter=isc.FilterBuilder.create({dataSource:a.dataSource,keyDown:function(){return a.keyDown()}});a._btnAdvFilter=advFiltRun.create({dataComp:a}).addProperties({click:function(){this.dataComp.doFilter()}});a._btnClearFilter=clrFilt.create({dataComp:a}).addProperties({click:function(){this.dataComp.clearFilter()}});return a._advFilter},_drawLayout:function(){var a=this;a._detailCanvas.addMember(a._createFilter());
a._detailCanvas.addMember(a._createCalendar());a.addTab({tabSelected:function(b,c,d,e,f,k){a.delayCall("focusInside")},title:a.dataSource.title,pane:a._detailCanvas,canClose:!1})},afterFilterFetch:function(a){},clearFilter:function(){this._advFilter.clearCriteria();this.doFilter()},doFilter:function(){var a=this;a._calendar.fetchData(a._advFilter.getCriteria(),function(b,c){a._calendar.getSelectedView().rebuild();a.afterFilterFetch(c)})},reload:function(){this._calendar.getSelectedView().isDrawn()&&
this._calendar.getSelectedView().rebuild()},cancel:function(a,b){this.resetTabEdit(0,!0);this.tabSet.removeTab(b?b:this._myTabName);this.destroy();a&&a(!0)},addRecord:function(a){App._addRecord(this,null,!1,a)},getDetail:function(a){if(!isA.emptyObject(a)){this._dynamicGridBar&&this._showTabBar();var b=this.dataSource.getPrimaryKeyFieldName();App._showDetailByPK(this.dataSource,a[b],this,this.type,null,null,null,this)}},focusInside:function(){var a=this._calendar.getSelectedView();a.getBody()&&a.focusInRow(0)},
dateIsWorkDaySK:function(a){var b=a.getFullYear(),c=a.getMonth(),d=a.getDate(),c=c+","+d,e=(b%19*19+24)%30,f=(5+b%4*2+b%7*4+6*e)%7,d=22+e+f,e=e+f-9,b=31>=d?DateUtil.createLogicalDate(b,2,d):25<e?DateUtil.createLogicalDate(b,3,e-7):DateUtil.createLogicalDate(b,3,e),d=new Date(b);d.setDate(b.getDate()-2);e=new Date(b);e.setDate(b.getDate()+1);return"0,1 0,6 4,1 4,8 6,5 7,29 8,1 8,15 10,1 10,17 11,24 11,25 11,26".split(" ").contains(c)||0==DateUtil.compareLogicalDates(d,a)||0==DateUtil.compareLogicalDates(e,
a)||0==a.getDay()||6==a.getDay()?!1:!0},initWidget:function(){this.Super("initWidget",arguments);this._detailCanvas=VLayout.create({height:"100%",width:"100%",dataSource:"",overflow:"visible"});this._customCalProps();this._drawLayout()}});
