ClassFactory.defineClass("DetailComponentTemplate","SmartTabSet").addProperties({height:"100%",width:"100%",overflow:"hidden",dataSource:null,parentDataSource:null,type:"",mode:"EDIT_BY_PK",initialValues:{},tabSet:null,_myTabName:null,brefField:"",brefValue:null,toTabSet:null,_detailCanvas:null,_asocGrids:[],_asocLayout:null,_pkCrit:{},_instanceID:null,_canSwitchLayout:!0,_hasAsocFields:!1,_ownerComp:null,_fromGridCom:null,_layoutDrawn:!1,dataSaved:function(a,b){!0===a&&(this.resetTabEdit(0,!0),this.tabSet.removeTab(this._myTabName));
isA.Function(this.detail.dataSaved)&&this.detail.dataSaved(b)},dataRemoved:function(a){this.resetTabEdit(0,!0);this.tabSet.removeTab(this._myTabName);isA.Function(this.detail.dataRemoved)&&this.detail.dataRemoved(a)},dataReloaded:function(a){isA.Function(this.detail.dataReloaded)&&this.detail.dataReloaded(a)},dataInitialized:function(a){isA.Function(this.detail.dataInitialized)&&this.detail.dataInitialized(a)},afterDrawDetail:function(){this._autoHideTabBar();isA.Function(this.detail.afterDrawDetail)&&
this.detail.afterDrawDetail()},keyDown:function(){var a=isc.EventHandler.getKey(),b;if("Q"==a&&isc.EventHandler.ctrlKeyDown()||"Escape"==a)this.cancel(),b=!1;if("R"==a&&isc.EventHandler.ctrlKeyDown()||"f5"==a)this.reload(),b=!1;if("A"==a&&isc.EventHandler.ctrlKeyDown()||"f2"==a)this.toolBar._btnAccept&&!this.toolBar._btnAccept.isDisabled()&&this.accept(),b=!1;if("E"==a&&isc.EventHandler.ctrlKeyDown()||"f6"==a)this.toolBar._btnEdit&&!this.toolBar._btnEdit.isDisabled()&&this.edit(),b=!1;if("S"==a&&
isc.EventHandler.ctrlKeyDown()||"f3"==a)this.toolBar._btnSave&&!this.toolBar._btnSave.isDisabled()&&this.save(),b=!1;if("K"==a&&isc.EventHandler.ctrlKeyDown()||"f4"==a)(this.detail._cloneSupport||this.dataSource._cloneSupport)&&this.toolBar._btnClone&&!this.toolBar._btnClone.isDisabled()&&this.clone(),b=!1;return b},_handleSmartFileCanvas:function(a){var b=this;this.detail.items.filter(function(a){return a.isA("SmartFileItem")}).forEach(function(c){c.handleSmartView(a,b.valuesManager.getValue(c.name))})},
_hasUploadItem:function(){for(var a=0;a<this.detail.items.length;a++){var b=this.detail.items[a];if(b.isA("UploadItem")||b.isA("SmartFileItem")&&b.canvas.items&&b.canvas.items[0].isA("UploadItem")){console.log(b.isA("UploadItem")?b._value:b.canvas.items[0]._value);if(b.isA("UploadItem")?b._value:b.canvas.items[0]._value)return!0;this._handleSmartFileCanvas(!1);break}}return!1},componentOnTabID:function(){return this.getID()},focusInside:function(){var a=this.detail.getFocusItem();!a||!1!==this.showTabBar&&
0!=this.getSelectedTabNumber()?!1===this.showTabBar||0==this.getSelectedTabNumber()?(a=1==this.detail.canEdit?this.detail.items.find({canFocus:!0,canEdit:!0})||this.detail.items.find({canFocus:!0,canEdit:null})||this.detail.items.find({canFocus:null,canEdit:!0})||this.detail.items.find({canFocus:null,canEdit:null}):this.detail.items.find({canFocus:!0})||this.detail.items.find({canFocus:null}),this.detail.focusInItem(a)):this.Super("focusInside"):this.detail.focusInItem(a)},setCanEdit:function(a){this.detail.setCanEdit(a);
this._handleSmartFileCanvas(a);this.delayCall("focusInside");!0===a?this.setTabEdit(0):this.resetTabEdit(0)},edit:function(){this.dataSource.setFieldAccess("edit",this.detail);this.setCanEdit(!0);this.toolBar.setIcons("edit")},_saveHasOne:function(){for(var a in this.dataSource.fields){var b=this.dataSource.getField(a),c=this.detail.getItem(a);"DetailHasOneItem"==b.editorType&&c.save(this,c)}},_save:function(a){this._saveHasOne();if(this.valuesManager.valuesHaveChanged()){var b=this,c=this.valuesManager.saveOperationType,
e=function(e,f){if(b.dataSource.handleError(e)){var h={operationType:c,data:isA.Array(f)?f:[f]};a||b.toolBar.setIcons("save");b._hasUploadItem()&&(h.data=b.dataSource.recordsFromObjects(f),b.dataSource.updateCaches(h),b._handleSmartFileCanvas(!1),b.valuesManager.setValues(f));b.parentDataSource&&b.parentDataSource.updateCaches(h);if("add"==c){var k=b.dataSource.getPrimaryKeyFieldName(),g=b.valuesManager.getValue(k);b.tabSet.setTabProperties(b._myTabName,{name:"_tabDetail_"+b.dataSource.ID+"_"+g,title:b.dataSource.title+
"["+b.valuesManager.getValue(b.dataSource.titleField)+"]"});b._myTabName="_tabDetail_"+b.dataSource.ID+"_"+g;b.valuesManager.setSaveOperationType("update");b.mode="EDIT_RECORD";b._pkCrit[b.dataSource.getPrimaryKeyFieldName()]=g;b._instanceID=g;if(b._asocGrids)for(g=0;g<b._asocGrids.length;g++){b._asocGrids[g].brefValue=b._asocGrids[g].brefValField?b.valuesManager.getValue(b._asocGrids[g].brefValField):b._instanceID;var l={};l[b._asocGrids[g].brefField]=b._asocGrids[g].brefValue;b._asocGrids[g].setRequiredProfile(l)}if(b.showTabBar)for(g=
1;g<b.tabs.length;g++)b.enableTab(g);for(k in b.dataSource.fields)"ListGridItem"==b.dataSource.fields[k].type&&b.detail.getField(k).setCanEdit(b.dataSource.fields[k].canEdit)}b.setCanEdit(!1);b.dataSaved(a,h.data)}};b.valuesManager.validate()&&(b._hasUploadItem()?b.dataSource.uploadFileToIframe(b.valuesManager,"add"==c?b.dataSource.addDataURL:b.dataSource.updateDataURL,e):b.valuesManager.saveData(e))}else isc.say(isc.i18nMessages["smartsfs.save.nochange"])},save:function(){this._save(!1)},accept:function(){this._save(!0)},
cancel:function(a,b){var c=this,e=function(e){e&&(c.resetTabEdit(0,!0),c.tabSet.removeTab(b?b:c._myTabName),c.destroy(),c=null);a&&a(e)};!this.toolBar._btnSave.isDisabled()&&this.valuesManager.valuesHaveChanged()||c._hasAnyTabEdit()?isc.ask(isc.i18nMessages["smartsfs.edit.cancel"],e):e(!0)},remove:function(){var a=this;isc.ask(isc.i18nMessages["default.button.delete.confirm.message"],function(b){b&&(a.valuesManager.setSaveOperationType("remove"),a.valuesManager.saveData(function(b,e){var d={operationType:"remove",
data:isA.Array(e)?e:[e]};a.parentDataSource&&a.parentDataSource.updateCaches(d);a.valuesManager.dataSource.updateCaches(d);a.dataRemoved(d.data)}))})},reload:function(a){var b=this,c=function(c){c?"add"==b.valuesManager.saveOperationType?(b.valuesManager.setValues(b.valuesManager.getOldValues()),isc.isA.Function(a)&&a()):b.valuesManager.fetchData(b._pkCrit,function(c,e){if(b._asocGrids)for(var h=0;h<b._asocGrids.length;h++)b._asocGrids[h].reload();b.toolBar.setIcons("reload");b.setCanEdit(!1);b.dataReloaded(e);
isc.isA.Function(a)&&a()}):isc.isA.Function(a)&&a()};!this.toolBar._btnSave.isDisabled()&&this.valuesManager.valuesHaveChanged()?isc.ask(isc.i18nMessages["default.reload.confirm.message"],c):c(!0)},addRecord:function(a){switch(this.type){case "bref":this._addBackRef();break;case "manyToMany":this._addManyToMany();break;default:App._addRecord(this,null,a,null,this.toTabSet)}},clone:function(){debugger;this.detail.valuesManager.getValues();this.addRecord(!0)},createAsocTab:function(a){var b=this;App.getDataSource(a.optionDataSource,
function(c){if(c){var e=b._instanceID,d=b.dataSource.getPrimaryKeyFieldName();a.valueField&&(e=b.valuesManager.getValue(a.valueField),d=a.valueField);var f=isc.GridComponentAny.create({dataSource:c,type:a.type,brefField:a.foreignKey,brefValue:e,brefValField:d,tabSet:b,_myTabName:"_asocGrid_"+c.ID,initialSort:a.initialSort,canFilter:a.canFilter,_gridTitle:a.title,_ownerComp:b});b._asocGrids.push(f);"SECTION"==b._asocLayout?(c="_asocGridsection_"+c.ID,b._sectionStack.addSection({name:c,title:a.title,
_titleEdit:'<div style="color:'+(App.get.config["smartsfs.tabcolor.edit"]||"red")+';">'+a.title+"</div>",_titleNormal:a.title,expanded:!0,resizeable:!0,items:[f]}),f._mySection=b._sectionStack.getSectionHeader(b._sectionStack.getSectionNumber(c)),b._sectionStack.collapseSection(c)):b.addTab({tabSelected:function(a,b,c,e,d,m){f.delayCall("focusInside")},name:"_asocGrid_"+c.ID,title:a.title,pane:f,canClose:!1,disabled:"NEW"==b.mode})}})},printPdf:function(){void 0!=this.detail.printPdf&&isA.Function(this.detail.printPdf)?
this.detail.printPdf(this):isc.RPCManager.exportContent(this,{skinName:App.get.config["smartsfs.skin"],pdfName:this.dataSource.ID,exportCSS:"@page {size: A4 landscape; }"})},switchLayout:function(){var a=this;switch(a._asocLayout){case "TABSET":var b=App.get.config["smartsfs.tabset.gridTabSet"].toString().toBoolean();a._sectionStack=isc.SectionStack.create(isc.addProperties({},{height:"100%",width:"100%",overflow:"auto",visibilityMode:"multiple"},a.dataSource.getFormProperties(a).sectionStackProperties));
!0===a.detail.canEdit&&a.delayCall("setTabEdit",0);a.updateTab(0,a._sectionStack);a._sectionStack.addSection({name:"section_detail",title:a.dataSource.title,_titleEdit:'<div style="color:'+(App.get.config["smartsfs.tabcolor.edit"]||"red")+';">'+a.dataSource.title+"</div>",_titleNormal:a.dataSource.title,expanded:!1,resizeable:!0,items:[a._detailCanvas]});a._mySection=a._sectionStack.getSectionHeader(a._sectionStack.getSectionNumber("section_detail"));for(var c=0;c<a._asocGrids.length;c++){a.selectTab("_asocGrid_"+
a._asocGrids[c].dataSource.ID);var e=a.getTabObject("_asocGrid_"+a._asocGrids[c].dataSource.ID);a.updateTab(e,null);a.removeTab(e);e="_asocGridsection_"+a._asocGrids[c].dataSource.ID;!1===a._asocGrids[c]._gridTabSet&&(a._asocGrids[c].toTabSet=a._asocGrids[c].toTabSet==a._asocGrids[c].tabSet?a._asocGrids[c]:a._asocGrids[c].toTabSet);a._asocGrids[c]._gridTabSet=!0;a._asocGrids[c]._showTabBar();a._sectionStack.addSection({name:e,title:a._asocGrids[c]._gridTitle,_titleEdit:'<div style="color:'+(App.get.config["smartsfs.tabcolor.edit"]||
"red")+';">'+a._asocGrids[c]._gridTitle+"</div>",_titleNormal:a._asocGrids[c]._gridTitle,expanded:!0,resizeable:!0,items:[a._asocGrids[c]]});a._asocGrids[c]._mySection=a._sectionStack.getSectionHeader(a._sectionStack.getSectionNumber(e));a._sectionStack.collapseSection("_asocGridsection_"+a._asocGrids[c].dataSource.ID);if(!1===b)for(e=1;e<a.tabs.length;e++){var d=a.getTabObject(e);if(d.pane&&d.pane.isA("DetailComponentTemplate")&&(d.pane.dataSource.ID==a._asocGrids[c].dataSource.ID||d.pane.parentDataSource&&
d.pane.parentDataSource.ID==a._asocGrids[c].dataSource.ID)){d.pane.tabSet=a._asocGrids[c];var f=d.pane;a.updateTab(d,null);a.removeTab(d);a._asocGrids[c].addTab({tabSelected:function(a,b,c,e,d,m){f.delayCall("focusInside")},name:d.name,title:d.title,icon:d.icon,pane:f,canClose:d.canClose})}}a._asocGrids[c]._hasAnyTabEdit()&&a._asocGrids[c]._mySection.setTitle(a._asocGrids[c]._mySection._titleEdit)}a._asocLayout="SECTION";a._hideTabBar();a._sectionStack.redraw();a._sectionStack.expandSection(0);break;
case "SECTION":a._sectionStack.expandSection(a._sectionStack.getSections(),function(){a.updateTab(0,a._detailCanvas);for(var b=0;b<a._asocGrids.length;b++){var c=a._asocGrids[b];c._gridTabSet=App.get.config["smartsfs.tabset.gridTabSet"].toString().toBoolean();!1===c._gridTabSet&&(c.toTabSet=c.toTabSet==c?a:c.toTabSet);a.addTab({tabSelected:function(a,b,e,d,f,g){c.delayCall("focusInside")},name:c._myTabName,title:c._gridTitle,pane:c,canClose:!1,disabled:"NEW"==a.mode});delete a._asocGrids[b]._mySection;
if(!1===a._asocGrids[b]._gridTabSet&&1<a._asocGrids[b].tabs.length)for(var e=1;e<a._asocGrids[b].tabs.length;e++){var d=a._asocGrids[b].tabs[e];d.pane.tabSet=a;var f=d.pane;a._asocGrids[b].updateTab(d,null);a._asocGrids[b].removeTab(d);a.addTab({tabSelected:function(a,b,c,e,d,g){f.delayCall("focusInside")},name:d.name,title:d.title,icon:d.icon,pane:f,canClose:d.canClose},a.getTabNumber(a._asocGrids[b]._myTabName)+1)}a._asocGrids[b]._hasAnyTabEdit()&&a.delayCall("setTabEdit",[a._asocGrids[b]._myTabName])}delete a._mySection;
a._asocLayout="TABSET";a._showTabBar();a.selectTab(0);a.redraw();a._detailCanvas.resizeTo(null,"100%");a._sectionStack.destroy();a._sectionStack=null})}},_createForm:function(a){var b=this;a=a||2;for(var c={},e=["15%"],d=1;d<a;d++)e.add("*");a={numCols:a,height:"100%",colWidths:e,width:"100%",overflow:"auto",border:App.get.config["smartsfs.detailBorder"],padding:10,dataSource:b.dataSource,canEdit:!1,formTabset:b.toTabSet,_ownerComp:b._ownerComp,_parentComp:b,focusInside:function(){b.focusInside()}};
null!=b.dataSource.formProperties&&(c=b.dataSource.getFormProperties(b));isc.addProperties(a,c);b.detail=isc.DynamicForm.create(a);b.valuesManager.addMember(b.detail);b.observe(b.detail,"draw","observer.afterDrawDetail()")},_createToolBar:function(){this.toolBar=DetailToolBarAny.create({dataComp:this})},_setValuesByMode:function(a){var b=this;"NEW"!=b.mode&&(b._instanceID=b.initialValues[b.dataSource.getPrimaryKeyFieldName()],b._pkCrit[b.dataSource.getPrimaryKeyFieldName()]=b.initialValues[b.dataSource.getPrimaryKeyFieldName()]);
switch(b.mode){case "NEW":b.delayCall("setCanEdit",[!0]);b.dataSource.initValues&&isc.addProperties(b.initialValues,b.dataSource.initValues);b.dataSource.setFieldAccess("add",b.detail);b.valuesManager.editNewRecord(b.initialValues);b.toolBar.setIcons("add");b.dataInitialized(b.initialValues);a();break;case "EDIT_BY_PK":b.valuesManager.fetchData(b._pkCrit,function(c,e){b.toolBar.setIcons("reload");b.dataInitialized(e);a()});break;case "EDIT_RECORD":b.valuesManager.editRecord(b.initialValues);b.toolBar.setIcons("reload");
b.dataInitialized(b.initialValues);a();break;default:a()}},_drawLayout:function(){var a=this;a._detailCanvas.addMember(a.toolBar);a._detailCanvas.addMember(a.detail);switch(a._asocLayout){case "SECTION":a._sectionStack||(a._sectionStack=isc.SectionStack.create(isc.addProperties({},{height:"100%",width:"100%",overflow:"auto",visibilityMode:"multiple"},a.dataSource.getFormProperties(a).sectionStackProperties)),a._sectionStack.addSection({name:"section_detail",title:a.dataSource.title,_titleEdit:'<div style="color:'+
(App.get.config["smartsfs.tabcolor.edit"]||"red")+';">'+a.dataSource.title+"</div>",_titleNormal:a.dataSource.title,expanded:!0,resizeable:!0,items:[a._detailCanvas]}),a._mySection=a._sectionStack.getSectionHeader(a._sectionStack.getSectionNumber("section_detail")),a.addTab({tabSelected:function(b,e,d,f,h,k){a.delayCall("focusInside")},title:a.dataSource.title,pane:a._sectionStack,canClose:!1}));break;default:a._asocLayout="TABSET",a.addTab({tabSelected:function(b,e,d,f,h,k){a.delayCall("focusInside")},
title:a.dataSource.title,pane:a._detailCanvas,canClose:!1})}for(var b in a.dataSource.fields)"agrmany"!=a.dataSource.fields[b].type&&"bref"!=a.dataSource.fields[b].type&&"manyToMany"!=a.dataSource.fields[b].type||a.dataSource.fields[b].viewRequiresRole&&!App.get.user.hasAnyRole(a.dataSource.fields[b].viewRequiresRole)||a.dataSource.fields[b].canCreateTab&&isA.Function(a.dataSource.fields[b].canCreateTab)&&0==a.dataSource.fields[b].canCreateTab(a)||(a._hasAsocFields=!0,a.createAsocTab(a.dataSource.fields[b]));
a._canSwitchLayout&&a._hasAsocFields&&a.toolBar.addLayoutSwitch();a._layoutDrawn=!0;a.delayCall("focusInside")},drawComponent:function(){},initWidget:function(){this.Super("initWidget",arguments);this.valuesManager=SmartSFSValuesManager.create({autoSynchronize:!0,dataSource:this.dataSource});this.toTabSet=this.toTabSet?this.toTabSet:this;this._asocGrids=[];this._asocLayout=null;this.dataSource.getFormProperties(this).asocLayout&&(this._asocLayout=this.dataSource.getFormProperties(this).asocLayout);
this._pkCrit={};this._instanceID=null;this._detailCanvas=VLayout.create({height:"100%",width:"100%",dataSource:"",overflow:"visible"});this.dataSource.setFieldAccess();this.drawComponent()}});
isc.ClassFactory.defineClass("DetailFormComponentAny","DetailComponentTemplate").addProperties({drawComponent:function(){var a=this;a.minHeight=App.get.config["smartsfs.detail.minHeight"]||10;if(isc.Browser.isDesktop){var b=15<Object.keys(a.dataSource.fields).length?4:2;Object.keys(a.dataSource.fields)}else b=2;a._createForm(b);a._createToolBar();a._setValuesByMode(function(){a._drawLayout()})}});
isc.ClassFactory.defineClass("DetailToolBarAny","VLayout").addProperties({height:30,overflow:"visible",dataComp:null,_opers:[],_setDisabledOpers:function(a){for(var b=0;b<this._opers.length;b++){var c=this._opers[b];c.setDisabled(a?!0:!c._canPerform(this.dataComp))}},setIcons:function(a){switch(a){case "edit":this._btnEdit.setDisabled(!0);this._btnSave.setDisabled(!1);this._btnAccept.setDisabled(!1);this._setDisabledOpers(!0);break;case "add":this._btnEdit.setDisabled(!0);this._btnSave.setDisabled(!1);
this._btnAccept.setDisabled(!1);this._btnRem.setDisabled(!0);this._btnClone.setDisabled(!0);this._setDisabledOpers(!0);break;case "save":this._btnEdit.setDisabled(!(this.dataComp.dataSource._isEditAble&&this.dataComp.dataSource.isEditAble(this.dataComp)));this._btnSave.setDisabled(!0);this._btnAccept.setDisabled(!0);this._btnRem.setDisabled(!(this.dataComp.dataSource._isRemoveAble&&this.dataComp.dataSource.isRemoveAble(this.dataComp)));this._setDisabledOpers(!1);break;case "reload":this._btnEdit.setDisabled(!(this.dataComp.dataSource._isEditAble&&
this.dataComp.dataSource.isEditAble(this.dataComp))),this._btnSave.setDisabled(!0),this._btnAccept.setDisabled(!0),this._btnRem.setDisabled(!(this.dataComp.dataSource._isRemoveAble&&this.dataComp.dataSource.isRemoveAble(this.dataComp))),this._setDisabledOpers(!1)}},addLayoutSwitch:function(){null!=this.dataComp._asocLayout&&(this._toolStrip.addMember(isc.LayoutSpacer.create({defaultWidth:"60%"})),this._switchLayout=BtnIcon.create({prompt:isc.i18nMessages["smartsfs.buttons.switch.prompt"],title:isc.i18nMessages["smartsfs.buttons.switch.prompt"],
showButtonTitle:!1,icon:"[SKIN]/FileBrowser/upOneLevel.png",dataComp:this.dataComp,click:function(){this.dataComp.switchLayout()}}),isc.Browser.isHandset||(this._switchLayout.showButtonTitle=!0,this._switchLayout.width=7*this._switchLayout.title.length+11),this._toolStrip.addMember(this._switchLayout))},initWidget:function(){this.Super("initWidget",arguments);if(this.dataComp){this._toolStrip=isc.ToolStrip.create();this._btnCancel=btnCancel.create({dataComp:this.dataComp});this._toolStrip.addMember(this._btnCancel);
this._toolStrip.addMember(ToolStripSeparator.create());this._btnAccept=btnAccept.create({dataComp:this.dataComp});this._toolStrip.addMember(this._btnAccept);this._btnSave=btnSave.create({dataComp:this.dataComp});this._toolStrip.addMember(this._btnSave);this._btnEdit=btnEdit.create({dataComp:this.dataComp}).addProperties({disabled:!this.dataComp.dataSource._isEditAble});this._toolStrip.addMember(this._btnEdit);this._btnRem=btnRem.create({dataComp:this.dataComp}).addProperties({disabled:!this.dataComp.dataSource._isRemoveAble});
this._toolStrip.addMember(this._btnRem);this._btnClone=btnCloneRec.create({dataComp:this.dataComp}).addProperties({disabled:!this.dataComp.dataSource._isCreateAble});this._toolStrip.addMember(this._btnClone);this._btnClone.hide();this.dataComp.dataSource._cloneSupport?this._btnClone.show():null!=this.dataComp.dataSource.formProperties&&this.dataComp.dataSource.getFormProperties(this.dataComp)._cloneSupport&&this._btnClone.show();this._toolStrip.addMember(ToolStripSeparator.create());this._btnRel=
btnDetailRel.create({dataComp:this.dataComp});this._toolStrip.addMember(this._btnRel);this._toolStrip.addMember(ToolStripSeparator.create());if(void 0==this.dataComp.dataSource.hasPdfReport||1==this.dataComp.dataSource.hasPdfReport)this._btnPdf=BtnIcon.create({title:"PDF",prompt:isc.i18nMessages["smartsfs.buttons.pdf.prompt"],icon:"[SKIN]/custom/pdf.png",dataComp:this.dataComp,click:function(){this.dataComp.printPdf()}}),this._toolStrip.addMember(this._btnPdf);this._btnPrint=BtnIcon.create({title:"Print",
prompt:isc.i18nMessages["smartsfs.buttons.print.prompt"],icon:"[SKIN]/actions/print.png",dataComp:this.dataComp,click:function(){this.dataComp.showPrintPreview()}});this._toolStrip.addMember(this._btnPrint);this._opers=[];if(0<this.dataComp.dataSource.operations.length){this.dataComp.dataSource.operations=this.dataComp.dataSource.operations.sortByProperty("position",!0);for(var a=0;a<this.dataComp.dataSource.operations.length;a++){var b=this.dataComp.dataSource.operations[a];"DETAIL"==b.placeOn.name&&
this.dataComp.dataSource.canPerformOperation(b.id)&&(b=IButton.create({prompt:b.prompt,title:b.title,showClippedTitleOnHover:!0,autoFit:!0,snapToGrid:!0,showButtonTitle:!0,icon:b.icon,dataComp:this.dataComp,_operationId:b.id,_canPerform:b.canPerform||function(){return this.dataComp.dataSource.canPerformOperation(this._operationId)},click:function(){this.dataComp.dataSource.performCustomOperation(this._operationId,this.dataComp,this.dataComp.valuesManager.getValues())}}),this._opers.push(b))}0<this._opers.length&&
(this._operStack=isc.ToolStrip.create({maxSize:0,dataComp:this.dataComp,maxResizeCount:0,_handleSize:function(a){this.maxResizeCount+=1;if(100<this.maxResizeCount)for(var b=0;b<this.members.length;b++){var d=this.members[b];d.setAutoFit(!0)}else{for(var f=0,h=(100/this.members.length).toString().split(".")[0]+"%",b=0;b<this.members.length;b++)d=this.members[b],f+=d.getVisibleWidth();1==a&&(this.maxSize=f);if(f>this.dataComp.getVisibleWidth())for(b=0;b<this.members.length;b++)d=this.members[b],d.setWidth(h),
d.setAutoFit(!1);else if(this.maxSize<this.dataComp.getVisibleWidth())for(b=0;b<this.members.length;b++)d=this.members[b],d.setWidth(d.defaultWidth),d.setAutoFit(!0)}}}),this._operStack.addMembers(this._opers),this.addMember(this._operStack),this._operStack.observe(this,"resized","observer._handleSize()"),this._operStack.delayCall("_handleSize",[!0]))}this.addMember(this._toolStrip)}}});
