FormItem.addProperties({showFocused:!0,blur:function(a,b){var c=isc.EventHandler.getKey();a&&a.handleFocus&&!EventHandler.leftButtonDown()&&"Tab"==c&&1==a.canEdit&&a.handleFocus(b,EventHandler.shiftKeyDown())},getParentSmartComp:function(){var a=this.parentElement||this.form.parentElement||this.form.grid.parentElement;return void 0==a?null:App._findParentSmartClass(a,"GridComponentAny")||App._findParentSmartClass(a,"DetailComponentTemplate")},getDisplayFieldName:function(){var a=this.getOptionDataSource(),
b=this.form?this.form.getDataSource():null;if(a){if(this.foreignDisplayField)return this.foreignDisplayField;if(null==b&&this.displayField)return this.displayField}else if(this.displayField)return this.displayField;if(this.displayField){b=b.getField(this.getFieldName());if(this.displayField!=(b?b.displayField:null)||null!=a.getField(this.displayField))return this.displayField;this.logInfo("Ignoring specified displayField:"+this.displayField+" - this doesn't  match any fields present in our optionDataSource:"+
a)}b=this.getValueFieldName();if(a&&a!=isc.DataSource.getDataSource(this.form?this.form.dataSource:null)&&(null!=this.displayField||a.getField(b)&&1==a.getField(b).hidden))return a.getTitleField()}});
isc.DateItem.addProperties({textAlign:"left",useTextField:!0,enforceDate:!0,_shouldAllowExpressions:function(){return!1},$85m:function(){return this._shouldAllowExpressions()},keyDown:function(a,b,c){("f3"==c||"f2"==c||"A"==c&&isc.EventHandler.ctrlKeyDown()||"S"==c&&isc.EventHandler.ctrlKeyDown())&&this.dateTextField&&this.dateTextField.blur(b,a)}});
ClassFactory.defineClass("SmartCombo","ComboBoxItem").addProperties({addUnknownValues:!1,_shouldAllowExpressions:function(){return!0},$85m:function(){return this._shouldAllowExpressions()},getAdvancedPickLisCriteria:function(a){if("AdvancedCriteria"!=a._constructor)if(void 0!=this.optionDataSource&&this.optionDataSource){var b=isc.DataSource.get(this.optionDataSource);a=b?b.convertDataSourceCriteria(a,"startsWith"):isc.DataSource.convertCriteria(a,"startsWith")}else a=isc.DataSource.convertCriteria(a,
"startsWith");return a||{}},getPickListFilterCriteria:function(){var a=this.Super("getPickListFilterCriteria");return this.getAdvancedPickLisCriteria(a)},getCriterion:function(a){this.addUnknownValues&&(this._shouldAllowExpressions=function(){return!0});a=this.Super("getCriterion",a);this.addUnknownValues&&(this._shouldAllowExpressions=function(){return!1});!a||"isNull"!=a.operator&&"notNull"!=a.operator||(a.fieldName=this.getDataPath()||this.getFieldName());return a||{}},getDisplayValue:function(){return this.Super("getDisplayValue",
arguments)},iconClick:function(a,b,c){a=b.optionDataSource;!a&&b.foreignKey&&(a=b.foreignKey.charAt(0).toUpperCase()+b.foreignKey.slice(1).split(".")[0]);App.getDataSource(a,function(a){a&&b.getValue()&&"detail"==c.name&&App._showDetailByPK(a,b.getValue(),App._findParentTabSet(b.grid||b.form))})},icons:[{name:"detail",title:"Detail",prompt:function(){return isc.i18nMessages["smartsfs.buttons.showdetail.prompt"]},src:"[SKIN]/DynamicForm/default_formItem_icon.png",disableOnReadOnly:!1}]});
isc.ClassFactory.defineClass("comboPickUp","SmartCombo").addProperties({id:"comboPickUp",pickerIconSrc:"[SKIN]/pickers/search_picker.png",showPickListOnKeypress:!1,addUnknownValues:!1,showPicker:function(){},iconClick:function(a,b,c){a=b.optionDataSource;!a&&b.foreignKey&&(a=b.foreignKey.charAt(0).toUpperCase()+b.foreignKey.slice(1).split(".")[0]);App.getDataSource(a,function(a){a&&("picker"==c.name?isc.listGridDialog.create({title:a.pluralTitle,dataSource:a,brefField:b.valueField,brefValue:null,
selectionType:"single",selectionAppearance:"rowStyle",_reqProfile:null,_resData:function(a){if(a){var c=a[0][b.getValueFieldName()],d=b.getDisplayFieldName();-1<d.indexOf(".")&&(d=d.split(".")[1]);var g={};g[c]=a[0][d];b.setValueMap(g);b.setValue(c)}}}):b.getValue()&&"detail"==c.name&&App._showDetailByPK(a,b.getValue(),App._findParentTabSet(b.grid||b.form)))})},icons:[{name:"detail",src:"[SKIN]/DynamicForm/default_formItem_icon.png",disableOnReadOnly:!1}]});
ClassFactory.defineClass("SmartComboAdd","SmartCombo").addProperties({showAdd:!0,isExtended:!1,dataSource:"",parentSmartComp:"",setDS:function(){var a=this,b=a.optionDataSource;!b&&a.foreignKey&&(b=a.foreignKey.charAt(0).toUpperCase()+a.foreignKey.slice(1).split(".")[0]);App.getDataSource(b,function(b){b&&(a.dataSource=b)})},getParentSmartComp:function(a){a=this.form.parentElement;return void 0==a?null:App._findParentSmartClass(a,"DetailComponentTemplate")},redraw:function(){if(1<this.icons.length&&
this.showAdd&&!this.isExtended){this.parentSmartComp=this.getParentSmartComp(this.form);var a=this.getWidth(),b=this.pickListWidth?this.pickListWidth:0;this.width=a+40;b-5<=a&&(this.pickListWidth=a-5);this.isExtended=!0}this.Super("redraw",arguments)},addRecord:function(a){App._addRecord(a,this)},iconClick:function(a,b,c){"add"==c.name?this.showAdd&&this.addRecord(this.parentSmartComp):b.getValue()&&"detail"==c.name&&App._showDetailByPK(b.dataSource,b.getValue(),App._findParentTabSet(b.grid||b.form))},
icons:[{name:"detail",title:"Detail",prompt:function(){return isc.i18nMessages["smartsfs.buttons.showdetail.prompt"]},src:"[SKIN]/DynamicForm/default_formItem_icon.png",disableOnReadOnly:!1},{name:"add",title:"Add",prompt:function(){return isc.i18nMessages["smartsfs.buttons.create.prompt"].messageArgs("")},src:"[SKIN]/custom/plus_icon.png",disableOnReadOnly:!0,showIf:function(a,b){0!=b.dataSource.canEdit?b.parentSmartComp&&"NEW"==b.parentSmartComp.mode&&(b.showAdd=!0):b.showAdd=!1;return b.showAdd}}],
init:function(){this.Super("init",arguments);this.setDS();this.observe(this.form,"draw","observer.redraw()")}});
isc.ClassFactory.defineClass("SmartFileItem","FileItem").addProperties({downloadIconSrc:"[SKIN]/actions/download.png",_updateFileDisabled:!0,viewIconSrc:"[SKIN]/actions/edit.png",viewFile:function(){this.setCanEdit(!0);this.redraw()},downloadFile:function(){isc.DS.get(this.getFormDataSource()).downloadSmartFile(this.getFormRecord()[this.name])},handleSmartView:function(a,b){var c=!1!==this.canSave&&a;this._updateFileDisabled=!c;this.setCanEdit(c?b?b.hasOwnProperty("filename")?!1:!0:!0:!1);this.delayCall("redraw")},
redraw:function(){var a=this.getValue();this.canvas&&(delete this.canvas.canvasItem,this.canvas.destroy(!0));void 0==this._createReadOnlyCanvas&&(this._createReadOnlyCanvas=this.$862);void 0==this._createEditableCanvas&&(this._createEditableCanvas=this.$863);this._isReadOnly=this.isReadOnly();this.setCanvas(this._isReadOnly?this._createReadOnlyCanvas():this._createEditableCanvas());this.setValue(a);this.Super("redraw",arguments)},_getViewIconSrc:function(){return this._updateFileDisabled?"&nbsp;":
isc.Canvas.imgHTML({src:this.viewIconSrc,width:16,height:16,extraCSSText:"cursor:"+isc.Canvas.HAND,extraStuff:"onclick='"+this.getID()+".viewFile()'"})},_getDownloadIconSrc:function(){return isc.Canvas.imgHTML({src:this.downloadIconSrc,width:16,height:16,extraCSSText:"cursor:"+isc.Canvas.HAND,extraStuff:" onclick='"+this.getID()+".downloadFile()'"})},getViewDownloadHTML:function(a,b){if(null==b)return null;var c=this.form.getDataSource(),c=c?c.getField(this.name):null,d=(a?a.filename:null)||b[this.name+
"_filename"];return!c||c.filenameSuppressed||null!=d&&!isc.isAn.emptyString(d)?"<nobr>"+this._getViewIconSrc()+"&nbsp;"+this._getDownloadIconSrc()+(d?"&nbsp;"+d:"")+"</nobr>":this.emptyCellValue}});
isc.ClassFactory.defineClass("DetailHasOneItem","CanvasItem").addProperties({showTitle:!1,showGroupTitle:!0,colSpan:4,shouldSaveValue:!0,fetchFormData:function(){var a={};this.getValue();a[this.valueField]=this.getValue();a=this.formDataSource.convertDataSourceCriteria(a,"exactCase");this.detail.valuesManager.fetchData(a)},getParentSmartComp:function(a){a=a.parentElement;return void 0==a?null:App._findParentSmartClass(a,"DetailComponentTemplate")},save:function(a,b){this.detail.valuesHaveChanged()&&
(this.detail.valuesManager.setValue("_dataType","hasOne"),a.valuesManager.setValue(b.name,this.detail.valuesManager.getChangedValues()))},createCanvas:function(a,b){this.valuesManager=SmartSFSValuesManager.create({autoSynchronize:!0,dataSource:this.formDataSource});this.formDataSource=DataSource.get(b.optionDataSource);for(var c=isc.Browser.isDesktop?15<Object.keys(this.formDataSource.fields).length?4:2:2,c=c||2,d=["15%"],e=1;e<c;e++)d.add("*");c={autoDraw:!1,groupLabelBackgroundColor:"none",colWidths:a.colWidths,
border:App.get.config["smartsfs.detailBorder"],isGroup:!0,groupBorderCSS:App.get.config["smartsfs.detailBorder"],margin:5,padding:10,dataSource:this.formDataSource,numCols:c};if(b.formItemProps){d={};try{for(var f in b.formItemProps)d[f]=App._evalPropertyValue(b.formItemProps[f])}catch(h){console.log("nezdarilo sa")}isc.addProperties(c,d)}this.detail=isc.DynamicForm.create(c);this.showGroupTitle&&this.detail.setGroupTitle(this.title);this.detail.valuesManager=SmartSFSValuesManager.create({autoSynchronize:!0,
dataSource:this.detail.dataSource});this.detail.valuesManager.addMember(this.detail);this.delayCall("fetchFormData");return this.detail}});
isc.ClassFactory.defineClass("ListGridItem","CanvasItem").addProperties({showTitle:!1,showGroupTitle:!0,colSpan:4,padding:10,minHeight:250,overflow:"inherit",groupLabelStyleName:"sectionHeaderopened",shouldSaveValue:!0,inTabSet:null,fetchGridItemData:function(){var a=this;this.fkId=this.form.getValue(this.formDataSource.getPrimaryKeyFieldName());var b={};b[this.valueField]=this.fkId;this.gridComp.setRequiredProfile(b);this.gridComp.grid.fetchData(this.gridComp._requiredProfile,function(){var b=a.gridComp.grid.getFieldByName(a.valueField);
a.gridComp.grid.hideField(b)})},createCanvas:function(a,b){this.valuesManager=SmartSFSValuesManager.create({autoSynchronize:!0,dataSource:this.optionDataSource});this.formDataSource=a.dataSource;this.inTabSet=this.inTabSet?this.inTabSet:a.formTabset;"NEW"==this.inTabSet.mode&&(this.canEdit=!1);var c=this,d={autoDraw:!1,overflow:this.overflow,groupLabelBackgroundColor:this.groupLabelBackgroundColor,groupLabelStyleName:this.groupLabelStyleName,border:App.get.config["smartsfs.detailBorder"],isGroup:!0,
padding:10,doAutoFetch:!1,groupBorderCSS:App.get.config["smartsfs.detailBorder"],dataSource:this.valuesManager.dataSource};if(b.formItemProps){var e={};try{for(var f in b.formItemProps)e[f]=App._evalPropertyValue(b.formItemProps[f])}catch(h){console.log("nezdarilo sa")}isc.addProperties(d,e)}this.valueField=b.foreignKey;this.gridComp=isc.GridComponentAny.create(d);this.gridComp.tabBar.hide();this.gridComp.addProperties({getDetail:function(){if(this.grid.getSelectedRecord()){var a=this.dataSource.getPrimaryKeyFieldName(),
a=this.grid.getSelectedRecord()[a];debugger;App._showDetailByPK(this.dataSource,a,c.inTabSet,this.type,this.brefField,this.brefValue,this._ownerComp,this);c.gridComp.tabBar.hide()}},addRecord:function(a){App._addRecord(c.gridComp,null,a,null,c.inTabSet)}});this.delayCall("fetchGridItemData");return this.gridComp}});
