isc.setAutoDraw(!1);Page.registerKey({ctrlKey:!1,keyName:"f2"},"return false");Page.registerKey({ctrlKey:!1,keyName:"f3"},"return false");Page.registerKey({ctrlKey:!1,keyName:"f4"},"return false");Page.registerKey({ctrlKey:!1,keyName:"f5"},"return false");Page.registerKey({ctrlKey:!1,keyName:"f6"},"return false");Page.registerKey({ctrlKey:!1,keyName:"f7"},"return false");Page.registerKey({ctrlKey:!1,keyName:"f8"},"return false");Page.registerKey({ctrlKey:!1,keyName:"f9"},"return false");
Page.registerKey({ctrlKey:!0,keyName:"W"},"return false");Page.registerKey({ctrlKey:!0,keyName:"T"},"return false");Page.registerKey({ctrlKey:!0,keyName:"Tab"},"return false");Page.registerKey({shiftKey:!0,ctrlKey:!0,keyName:"T"},"return false");Page.registerKey({altKey:!0,ctrlKey:!1,shiftKey:!1,keyName:"Arrow_Left"},"return false");isc.SimpleType.getType("boolean").compareValues=function(b,a,c){return b?a?0:1:a?-1:!1===b?!1===a?0:-1:!1===a?1:0};
isc.SimpleType.getType("text").compareValues=function(b,a,c){return void 0!=b&&null!=b&&""!=b||void 0!=a&&null!=a&&""!=a?b!=a?b>a?1:-1:0:0};isc.SimpleType.getType("localeFloat").compareValues=function(b,a,c){return b==a?(b=isc.isA.Number(b),a=isc.isA.Number(a),b&&!a?-1:!b&&a?1:0):null!=b&&""!=b&&void 0!==b||null!=a&&""!=a&&void 0!==a?b>a?-1:1:0};
RPCManager.addClassProperties({useSimpleHttp:!0,showPrompt:!0,promptStyle:"dialog",loginRequired:function(b,a,c){App.get.user.enabled=!1;App.get.loadUser(void 0,void 0,!0,function(){RPCManager.resendTransaction(b);App.get.userLoginSucces()})},handleTransportError:function(b,a,c,d){isc.say(d)}});
ListGrid.addProperties({exportWrapHeaderTitles:!0,exportHeaderHeights:!0,exportAlternateRowBGColor:"#d0dff6",autoFitWidthApproach:"both",autoFitDateFields:"both",autoFitTimeFields:"both",fetchRelatedData:function(b,a,c,d){var f=isc.isA.DataSource(a)?a:isc.isA.String(a)?isc.DS.get(a):isc.isA.Canvas(a)?a.dataSource:null;if(f){a=this.getDataSource().getTreeRelationship(f,null,!0);for(var f=a.parentIdFields,e=a.idFields,k={},l=0;l<f.length;l++)k[f[l]]=b[e[l]];b=a.childDS.convertDataSourceCriteria(k);
this.fetchData(b,c,d)}else this.logWarn("schema not understood: "+this.echoLeaf(a))},refreshData_DEPRECATED:function(b){if(this.getDataSource()){var a=this.getData();this.dataObjectSupportsFilter(a)||(a=this.originalData);if(a&&a.fetchIsPending&&a.fetchIsPending())this.logWarn("A fetch for this component is currently pending, please try again later.");else{var c=this.getDataSource(),d=this.getVisibleRows(),f=this.getSelectedState(),e=d[0]-a.resultSize,d=d[1]+a.resultSize;0>e&&(e=0);e={startRow:e,
endRow:d,sortBy:this.getSort(),showPrompt:!1,componentId:this.getID()};(d=a.context)&&d.textMatchStyle&&(e.textMatchStyle=d.textMatchStyle);d&&d.operationId&&(e.operationId=d.operationId);this.implicitCriteria&&(e.dbcImplicitCriteria=isc.shallowClone(this.implicitCriteria));var k=isc.clone(a.getCriteria()),k=isc.DS.compressNestedCriteria(isc.DS.combineCriteria(k,isc.shallowClone(this.implicitCriteria))),l=isc.clone(a.getSort());c.fetchData(this.getCriteria(),function(a,d,e){var g=this.data;this.dataObjectSupportsFilter(g)||
(g=this.originalData);var h=isc.DS.compressNestedCriteria(isc.DS.combineCriteria(g.getCriteria(),g.getImplicitCriteria?g.getImplicitCriteria():{})),n=g.getSort(),h=0===g.compareCriteria(h,k)||g.compareSort?g.compareSort(n,l):!1;if(g&&g.fetchIsPending&&g.fetchIsPending()&&h)this.logDebug("refreshData aborted as a fetch had been issued while waiting for refreshData to complete.");else{g=a.data;h=[];h.length=a.totalRows;for(var n=a.startRow||0,m=0;m<g.length;m++)h.set(n+m,g.get(m));g=c.getResultSet({dataSource:this.getDataSource(),
initialLength:a.totalRows,initialData:h,sortSpecifiers:this.getSort(),criteria:this.getCriteria(),context:this.data&&isc.isA.ResultSet(this.data)?this.data.context:null});h=this.preserveEditsOnSetData;this.preserveEditsOnSetData=!0;this.setData(g);this.preserveEditsOnSetData=h;this.setSelectedState(f);b&&b(a,d,e)}}.bind(this),e)}}else this.logError("In order to refresh data a dataSource has to be specified for the component '"+this.ID+"'.")}});
FilterEditorBody.addProperties({keyDown:function(){debugger;return this.parentElement.keyDown()}});DynamicForm.addProperties({errorOrientation:"right",itemHoverWidth:"25%",handleFocus:function(b,a){if(b.hasOwnProperty("fieldPosition")&!this.isSearchForm){for(var c=this.items.length+1,d=-1,f=0,e=0;e<this.items.length;e++)0==this.items[e].canEdit||this.items[e].disabled||(e<c&&(c=e),e>d&&(d=e)),this.items[e].fieldPosition==b.fieldPosition&&(f=e);a&&f<=c&&this.focusInItem(this.items[d]);!a&&f>=d&&this.focusInItem(this.items[c])}}});
ClassFactory.defineClass("SmartSFSValuesManager","ValuesManager").addProperties({saveData:function(){var b=this.getValues(),a={__ref:!0,__module:!0},c;for(c in b)isc.isA.Function(b[c])||1!=a[c]&&(isc.isAn.Instance(b[c])||isc.isA.Class(b[c])||void 0==b[c]&&(b[c]=null));this.setValues(b);this.Super("saveData",arguments)},fieldValuesAreEqual_DEPRECATED:function(b,a,c){if(null!=b){if(!0===b.propertiesOnly)return!0;isc.isAn.Object(b)||(b=this.getUnderlyingField(b)||b);if(b.multiple&&isc.isAn.Array(a)&&
isc.isAn.Array(c)){if(a.length!=c.length)return!1;for(var d=!0,f=0;f<a.length;f++)if(!this.fieldValuesAreEqual(b,a[f],c[f])){d=!1;break}return d}if(null!=b.type){if((d=isc.SimpleType.getType(b.type))&&d.compareValues)return 0==d.compareValues(a,c,b);if(isc.SimpleType.inheritsFrom(b.type,"datetime")){if(isc.isA.Date(a)&&isc.isA.Date(c))return 0==Date.compareDates(a,c)}else if(isc.SimpleType.inheritsFrom(b.type,"date")){if(isc.isA.Date(a)&&isc.isA.Date(c))return 0==Date.compareLogicalDates(a,c)}else if("valueMap"==
b.type){if(isc.isAn.Array(a)&&isc.isAn.Array(c))return a.equals(c);if(isc.isAn.Object(a)&&isc.isAn.Object(c)){for(f in a)if(c[f]!=a[f])return!1;for(var e in c)if(a[e]!=c[e])return!1;return!0}}}}return!isc.isAn.Object(b)&&isc.isA.Date(a)&&isc.isA.Date(c)?a.logicalDate||c.logicalDate?0==isc.Date.compareLogicalDates(a,c):a.logicalTime||c.logicalTime?0==isc.Time.compareLogicalTimes(a,c):a.getTime()==c.getTime():a==c||!(null!=a&&""!=a&&void 0!==a||null!=c&&""!=c&&void 0!==c)||null==b&&(isc.isAn.Object(a)||
isc.isAn.Object(c))&&(isA.emptyObject(a)&&isA.emptyObject(c)||void 0==a||void 0==c||a["class"]&&c["class"]&&a["class"]==c["class"])?!0:!1}});
isc.EventHandler.addClassProperties({_handleTouchEnd:function(b){debugger;var a=isc.EH;a.DOMevent=b;var c=a.getMouseEventProperties(b);if(a.eventHandledNatively(b.type,b.target))return a._handledNativelyReturnVal;a._handledTouch==a._touchEventStatus.TOUCH_STARTED&&(a._handledTouch=a._touchEventStatus.TOUCH_ENDING);!1!==a.handleEvent(c.target,a.TOUCH_END)&&(c.originalType=a.TOUCH_END,c.eventType=a.MOUSE_UP,a._handleMouseUp(b,!0));a._handledTouch==a._touchEventStatus.TOUCH_ENDING&&(a._handledTouch=
a._touchEventStatus.TOUCH_COMPLETE);null!=a._longTouchTimer&&(isc.Timer.clear(a._longTouchTimer),a._longTouchTimer=null);if(!a._shouldIgnoreTargetElem(b.target&&(1==b.target.nodeType?b.target:b.target.parentElement))&&b.cancelable)return b.preventDefault(),b.stopPropagation(),swiping=!0,!1},$77r:function(b){return this._handleTouchEnd(b)}});String.prototype.messageArgs=function(){var b=arguments;return this.replace(/\{(\d+)\}/g,function(a,c){return b[c]})};
String.prototype.toBoolean=function(){if("true"==this.toLowerCase())return!0;if("false"==this.toLowerCase())return!1};
