isc.ClassFactory.defineClass("GridComponentAny","SmartTabSet").addProperties({height:"100%",width:"100%",dataSource:"",overflow:"hidden",mode:null,_ownerComp:null,type:"",brefField:null,brefValue:null,parentTabSet:null,tabSet:null,_myTabName:null,_gridCanvas:null,initialSort:[],canFilter:!0,doAutoFetch:!0,toTabSet:null,_requiredProfile:{},_userSettSupport:!1,_recordsDropped:function(a,b){var c=this;if(c.reorderIndexField){a[0][c.reorderIndexField]||(a[0][c.reorderIndexField]=1);var d=a[0][c.reorderIndexField]-
1>b?b:a[0][c.reorderIndexField]-1,f=c.dataSource.getField(c.reorderIndexField).title;isc.ask(isc.i18nMessages["smartsfs.reorder.confirm"].messageArgs(f),function(a){if(a)for(a=d;a<c.getTotalRows();a++){var b=c.getRecord(a);b[c.reorderIndexField]=a+1;c.updateData(b)}c.sort(c.reorderIndexField)})}},afterReloadFetch:function(){isA.Function(this.grid.afterReloadFetch)&&this.grid.afterReloadFetch()},afterFilterFetch:function(){isA.Function(this.grid.afterFilterFetch)&&this.grid.afterFilterFetch()},afterClearFilter:function(){isA.Function(this.grid.afterClearFilter)&&
this.grid.afterClearFilter()},afterInitFetch:function(){isA.Function(this.grid.afterInitFetch)&&this.grid.afterInitFetch()},keyDown:function(){var a=isc.EventHandler.getKey(),b;("Q"==a&&isc.EventHandler.ctrlKeyDown()||"Escape"==a)&&this.cancel(function(a,d){b=!a;!a&&d._ownerComp.isA("DetailComponentTemplate")&&d._ownerComp.cancel(function(a){b=!a})});"A"==a&&isc.EventHandler.ctrlKeyDown()&&(this.hasOwnProperty("advFilter")&&1==this.advFilter.isVisible()&&this.advFilter.clearCriteria(),this.grid.setFilterEditorCriteria(null),
this.grid.filterData(),b=!1);if("F"==a&&isc.EventHandler.ctrlKeyDown()||"f4"==a)this.hasOwnProperty("advFilter")&&1==this.advFilter.isVisible()?this.doFilter("advanced"):this.doFilter("normal"),b=!1;if("R"==a&&isc.EventHandler.ctrlKeyDown()||"f5"==a)this.reload(),b=!1;if("D"==a&&isc.EventHandler.ctrlKeyDown()||"f6"==a)this.getDetail(),b=!1;if("I"==a&&isc.EventHandler.ctrlKeyDown()||"f7"==a)this.toolBar._btnAdd&&!this.toolBar._btnAdd.isDisabled()&&this.addRecord(),b=!1;if("E"==a&&isc.EventHandler.ctrlKeyDown()||
"f8"==a)this.exportData("xls"),b=!1;if("P"==a&&isc.EventHandler.ctrlKeyDown()||"f9"==a)this.toolBar._btnPdf&&!this.toolBar._btnPdf.isDisabled()&&this.printPdf(),b=!1;if("K"==a&&isc.EventHandler.ctrlKeyDown()||"f4"==a)(this.grid._cloneSupport||this.dataSource._cloneSupport)&&this.toolBar._btnClone&&!this.toolBar._btnClone.isDisabled()&&this.clone(),b=!1;return 0==b?b:this.tabSet.keyDown()},componentOnTabID:function(){return this.getID()},focusInside:function(){0==this.getSelectedTabNumber()?this.canFilter&&
!isc.Browser.isHandset?this.grid.focusInFilterEditor():this.grid.bodies&&this.grid.focusInRow(0):this.Super("focusInside")},changeData:function(a){this.dataSource.fetchRecord(a)},cancel:function(a,b){var c=this,d=b?b:c.tabSet.getTab(c._myTabName),f=function(a){!0===a&&(c.resetTabEdit(0,!0),c.tabSet.removeTab(d))};1==d.canClose&&(c._hasAnyTabEdit()?isc.ask(isc.i18nMessages["smartsfs.edit.cancel"],f):f(!0));a&&a(d.canClose,c)},setRequiredProfile:function(a){a&&(this._requiredProfile="AdvancedCriteria"==
a._constructor?a:this.dataSource.convertDataSourceCriteria(a,"exactCase"),this.grid.isDrawn()&&this.clearFilter())},remReqProfileFromCrit:function(a){a="AdvancedCriteria"==a._constructor?a:this.dataSource.convertDataSourceCriteria(a,"exactCase");if(this._requiredProfile&&Object.getOwnPropertyNames(this._requiredProfile).length)for(var b=this._requiredProfile.criteria.getProperty("fieldName"),c=[],d=0;d<b.length;d++)c=a.criteria.findAll("fieldName",b[d]),null!=c&&0<c.length&&a.criteria.removeList(c);
return a},getCriteria:function(a){var b={};switch(a){case "advanced":b=this.advFilter.getCriteria();break;case "normal":b=this.grid.getFilterEditorCriteria();break;default:b=this.grid.getFilterEditorCriteria(),b||(b=this.advFilter.getCriteria(),0==b.criteria.length&&(b={}))}if(this._requiredProfile&&Object.getOwnPropertyNames(this._requiredProfile).length){a="AdvancedCriteria"==this._requiredProfile._constructor?this._requiredProfile:this.dataSource.convertDataSourceCriteria(this._requiredProfile,
"exactCase");var c=!0;if(b.hasOwnProperty("criteria"))for(var b=this.remReqProfileFromCrit(b),d=0;d<b.criteria.length;d++)if(b.criteria[d].fieldName==this.brefField){c=!1;break}c&&(b=DataSource.combineCriteria(a,b))}return b},doFilter:function(a){var b=this;b.grid.filterData(this.getCriteria(a),function(a,d){b.afterFilterFetch()})},clearFilter:function(){var a=this;this.advFilter.clearCriteria();this.grid.setFilterEditorCriteria({});if(!this.advFilter.isVisible())for(var b=0;b<this.grid.fields.length;b++){var c=
this.grid.fields[b];void 0!=c.operator&&null!=c.operator&&this.grid.setFieldProperties(c.name,{operator:null})}!1===a.grid.doAutoFetch?(a.grid.setData([]),a.afterClearFilter()):0<this.dataSource.convertDSCriteria(this._requiredProfile).criteria.length?this.toolBar._btnUserSetting.usCriteria?this.grid.filterData(DataSource.combineCriteria(this.dataSource.convertDSCriteria(this._requiredProfile),this.remReqProfileFromCrit(this.toolBar._btnUserSetting.getUSCriteria())),function(b,c){a.afterClearFilter()}):
this.grid.filterData(this._requiredProfile,function(b,c){a.afterClearFilter()}):this.grid.filterData(this.toolBar._btnUserSetting.getUSCriteria(),function(b,c){a.afterClearFilter()})},_addBackRef:function(){var a=this;isc.listGridDialog.create({title:this.dataSource.pluralTitle,dataSource:this.dataSource,brefField:a.brefField,brefValue:a.brefValue,_ownerComp:a._ownerComp,_reqProfile:{_constructor:"AdvancedCriteria",operator:"and",criteria:[{operator:"or",criteria:[{fieldName:a.brefField,operator:"notEqual",
value:a.brefValue},{fieldName:a.brefField,operator:"isNull"}]}]},_resData:function(b){if(b)for(var c=0;c<b.length;c++)a.brefValue&&(b[c][a.brefField]=a.brefValue,a.grid.addData(b[c],null,{operationType:"update"}))}})},remove:function(){if("manyToMany"==this.type&&this.brefValue){var a=this.grid.getSelectedRecord();if(null==a)isc.warn(isc.i18nMessages["default.noRowSelected.prompt"]);else{var b={};b[this.brefField]=this.brefValue;this.dataSource.removeData(a,null,{params:b})}}if("bref"==this.type)if(a=
this.grid.getSelectedRecords())for(b=0;b<a.length;b++)this.brefValue&&(a[b][this.brefField]=null,this.grid.removeData(a[b],null,{operationType:"update"}));else isc.warn(isc.i18nMessages["default.noRowSelected.prompt"])},_addManyToMany:function(){var a=this,b=function(b){if(b)for(var c=0;c<b.length;c++)if(a.brefValue){var h=b[c],e={};e[a.brefField]=a.brefValue;a.dataSource.addData(h,null,{params:e});c+1==b.length&&a.delayCall("reload",null,100)}},c={_constructor:"AdvancedCriteria",operator:"and",criteria:[]};
App.getDataSource(a.dataSource.detailFormDS,function(d){for(var f=d.getPrimaryKeyFieldName(),h=0;h<a.grid.data.getLength();h++)c.criteria.push({fieldName:f,operator:"notEqual",value:a.grid.data.get(h)[f]});isc.listGridDialog.create({title:d.pluralTitle,dataSource:d,brefField:null,brefValue:null,_ownerComp:a._ownerComp,_reqProfile:c,_resData:b})})},addRecord:function(a){switch(this.type){case "bref":this._dynamicGridBar&&this._showTabBar();this._addBackRef();break;case "manyToMany":this._addManyToMany();
break;default:this._dynamicGridBar&&this._showTabBar(),App._addRecord(this,null,a,null,this.toTabSet)}},clone:function(){debugger;this.grid.getSelectedRecord();this.addRecord(!0)},getDetail:function(){if(this.grid.getSelectedRecord()){this._dynamicGridBar&&this._showTabBar();var a=this.dataSource.getPrimaryKeyFieldName(),a=this.grid.getSelectedRecord()[a];App._showDetailByPK(this.dataSource,a,this.toTabSet,this.type,this.brefField,this.brefValue,this._ownerComp,this)}},reload:function(){var a=this;
this.grid.initialSort&&0<this.grid.initialSort.length&&this.grid.setSort(this.grid.initialSort);this.grid.isDrawn()&&this.grid.refreshData(function(){a.toolBar.setIcons();a.afterReloadFetch()})},importData:function(a){"csv"==a&&SmartSource.performCustomOperation("csvImport",this,{})},exportData:function(a){var b=this;"xls"==a&&isA.Function(this.grid.printXls)?this.grid.printXls(this):"csv"==a&&isA.Function(this.grid.printCsv)?this.grid.printCsv(this):"xls"==a?SmartSource.performCustomOperation("xlsExport",
b,{}):"csv"==a?SmartSource.performCustomOperation("csvExport",b,{}):(this.grid.invalidateCache(),this.grid.filterData(this.getCriteria(),function(){b.grid.exportClientData({exportAs:a,exportFilename:b.dataSource.ID})},{endRow:App.get.config["sc.xlsexport.size"]?App.get.config["sc.xlsexport.size"]:1E3}))},printPdf:function(){void 0!=this.grid.printPdf&&isA.Function(this.grid.printPdf)?this.grid.printPdf(this):isc.RPCManager.exportContent(this.grid,{skinName:"EnterpriseBlue",pdfName:this.dataSource.ID,
exportCSS:"@page {size: A4 landscape; }"})},setGrid:function(){var a=this,b={};if(null!=a.dataSource.gridProperties){var c=isA.String(a.dataSource.gridProperties)?isc.JSON.decode(a.dataSource.gridProperties):a.dataSource.gridProperties,d;for(d in c)b[d]=App._evalPropertyValue(c[d])}void 0==b.doAutoFetch&&(b.doAutoFetch=this.doAutoFetch);c={height:"100%",width:"100%",canEdit:!1,overflow:"auto",mode:a.mode,rowEndEditAction:"same",listEndEditAction:"done",autoFitFieldWidths:!0,alternateRecordStyles:!0,
autoFetchData:!1,showFilterEditor:a.canFilter?!0:!1,allowFilterExpressions:!0,canAddFormulaFields:!0,canAddSummaryFields:!0,canReorderRecords:null==b.reorderIndexField?!1:!0,filterEditorSubmit:function(b){a.doFilter();return!1},filterEditorProperties:{editorKeyDown:function(){return a.keyDown()}},filterLocalData:!1,fetchDelay:500,dataSource:a.dataSource,recordDoubleClick:function(){a.getDetail()},_afterDrawGrid:function(b){this.isDrawn()&&(!0===this.doAutoFetch?this.fetchData(a._requiredProfile,function(){"normal"!=
a.type&&a.grid.getField(a.brefField)&&a.grid.hideField(a.brefField);a.toolBar.setIcons();a.toolBar._btnUserSetting.usdf.setDefault();isc.Browser.isHandset?a.grid.focusInRow(0):a.grid.focusInFilterEditor();isc.isA.Function(b)&&b();a.afterInitFetch()}):("normal"!=a.type&&a.grid.getField(a.brefField)&&a.grid.hideField(a.brefField),a.toolBar.setIcons(),a.toolBar._btnUserSetting.usdf.setDefault(),isc.Browser.isHandset?a.grid.focusInRow(0):a.grid.focusInFilterEditor(),isc.isA.Function(b)&&b()))},afterDrawGrid:function(){this._afterDrawGrid()},
initialSort:a.initialSort,_ownerComp:a._ownerComp,_parentComp:a};isc.addProperties(c,b);a.grid=isc.ListGrid.create(c);a.grid.observe(a.grid,"draw","observer.afterDrawGrid()");null!=a.grid.reorderIndexField&&(a.grid.recordsDropped=a._recordsDropped)},initRequiredProfile:function(){if("normal"!=this.type){var a={};a[this.brefField]=null==this.brefValue?"-1":this.brefValue;this._requiredProfile=this.dataSource.convertDataSourceCriteria(a,"exactCase")}void 0!=this.dataSource.customProfile&&null!=this.dataSource.customProfile&&
(a={},a=isA.Function(this.dataSource.customProfile)?this.dataSource.customProfile(this):this.dataSource.customProfile,a="AdvancedCriteria"==a._constructor?a:this.dataSource.convertDataSourceCriteria(a,"exactCase"),this._requiredProfile&&Object.getOwnPropertyNames(this._requiredProfile).length?this._requiredProfile=DataSource.combineCriteria(this._requiredProfile,a):this._requiredProfile=a)},setAdvFilter:function(){var a=this;a.advFilter=isc.FilterBuilder.create({dataSource:a.dataSource,keyDown:function(){a.keyDown()}});
a.advFilter.hide()},setToolBar:function(){this.toolBar=GridToolBarAny.create({dataComp:this})},setMembers:function(){var a=this;a.valuesManager=SmartSFSValuesManager.create({autoSynchronize:!0,dataSource:a.dataSource});a.valuesManager.addMember(a.grid);a._gridCanvas.addMember(a.advFilter);a._gridCanvas.addMember(a.toolBar);a._gridCanvas.addMember(a.grid);a.addTab({tabSelected:function(b,c,d,f,h,e){a.delayCall("focusInside")},pane:a._gridCanvas,canClose:!1,title:isc.i18nMessages["default.grid.tabtitle"]+
" "+a.dataSource.pluralTitle})},initWidget:function(){this.Super("initWidget",arguments);this.toTabSet=this.toTabSet?this.toTabSet:this._gridTabSet?this:this.tabSet;this._userSettSupport=App.get.config["smartsfs.userSetting.supported"].toString().toBoolean()||isc.Browser.isHandset&&App.get.config["smartsfs.userSetting.handset.supported"].toString().toBoolean()||!1;this._gridCanvas=VLayout.create({height:"100%",width:"100%",dataSource:"",overflow:"hidden"});this.dataSource?(this.initRequiredProfile(),
this.setAdvFilter(),this.setToolBar(),this.setGrid(),this.setMembers()):isc.say("NEDOSIEL DATASOURCE!!!!")}});
isc.ClassFactory.defineClass("GridToolBarAny","VLayout").addProperties({height:30,overflow:"visible",dataComp:null,_tsUserSetting:null,_opers:[],_handleSize:function(){for(var a=0,b=0,c=0;this._toolStrip.members.length>c;c++)"iconButton"==this._toolStrip.members[c].baseStyle&&"hidden"!=this._toolStrip.members[c].visibility&&b++;if(this._btnUserSetting)if(App.get.splitPane.detailToolStrip.getVisibleWidth()<494-24*(9-b)&&this._btnUserSetting){for(c=0;this.members.length>c;c++)this.members[c]==this._tsUserSetting&&
(a=1);0==a&&(this._tsUserSetting=isc.ToolStrip.create({}),this._tsUserSetting.addMember(this._btnUserSetting),this._toolStrip.removeMember(this._btnUserSetting),this._btnUserSetting.usdf.getField("name").setWidth(this._btnUserSetting.usdf.getField("name").getVisibleWidth()-24*(9-b)),this.addMember(this._tsUserSetting))}else{for(c=0;this._toolStrip.members.length>c;c++)this._toolStrip.members[c]==this._btnUserSetting&&(a=1);0==a&&(this._btnUserSetting.usdf.getField("name").setWidth(182),this._toolStrip.addMember(this._btnUserSetting),
this.removeMember(this._tsUserSetting))}},_setDisabledOpers:function(a){for(var b=0;b<this._opers.length;b++){var c=this._opers[b];c.setDisabled(a?!0:!c._canPerform(this.dataComp))}},setIcons:function(){this._btnAdd&&this._btnAdd.setDisabled(!(this.dataComp.dataSource._isCreateAble&&this.dataComp.dataSource.isCreateAble(this.dataComp)));this._btnRemove&&this._btnRemove.setDisabled(!(this.dataComp.dataSource._isRemoveAble&&this.dataComp.dataSource.isRemoveAble(this.dataComp)));this._setDisabledOpers(!1)},
initWidget:function(){this.Super("initWidget",arguments);var a=this;if(this.dataComp){this._toolStrip=isc.ToolStrip.create();"normal"==this.dataComp.type&&(this._btnCancel=btnCancel.create({dataComp:this.dataComp}),this._toolStrip.addMember(this._btnCancel));0!=this.dataComp.canFilter&&(this._btnFilter=btnFilter.create({dataComp:this.dataComp}).addProperties({click:function(){this.dataComp.doFilter("normal")}}),this.dataComp.advFilter&&(this._btnAdvFilter=advFiltRun.create({dataComp:this.dataComp}).addProperties({click:function(){this.dataComp.doFilter("advanced")}}),
this._btnSwitchFilter=advFilt.create({dataComp:this.dataComp}).addProperties({click:function(){this.dataComp.advFilter.isVisible()?(this.dataComp.advFilter.clearCriteria(),this.dataComp.advFilter.hide(),a._btnAdvFilter.hide(),a._btnFilter.show(),this.dataComp.grid.setShowFilterEditor(!0)):(this.dataComp.advFilter.show(),a._btnAdvFilter.show(),a._btnFilter.hide(),this.dataComp.grid.setShowFilterEditor(!1),this.dataComp.grid.setFilterEditorCriteria(null))}}),this._toolStrip.addMember(this._btnSwitchFilter),
this._toolStrip.addMember(this._btnAdvFilter),this.dataComp.advFilter.hide(),this._btnAdvFilter.hide()),this._toolStrip.addMember(this._btnFilter),this._btnClearFilter=clrFilt.create({dataComp:this.dataComp}).addProperties({click:function(){this.dataComp.clearFilter()}}),this._toolStrip.addMember(this._btnClearFilter),this._toolStrip.addMember(ToolStripSeparator.create()));this._btnDetail=btnDetail.create({dataComp:this.dataComp}).addProperties({click:function(){this.dataComp.getDetail()}});this._toolStrip.addMember(this._btnDetail);
if(0!=this.dataComp.dataSource.canEdit){this._btnAdd=btnAdd.create({dataComp:this.dataComp}).addProperties({click:function(){this.dataComp.addRecord()},disabled:!this.dataComp.dataSource._isCreateAble});this._toolStrip.addMember(this._btnAdd);if("manyToMany"==this.dataComp.type||"bref"==this.dataComp.type)this._btnRemove=btnRem.create({dataComp:this.dataComp}).addProperties({disabled:!this.dataComp.dataSource._isRemoveAble}),this._toolStrip.addMember(this._btnRemove);this._btnClone=btnCloneRec.create({dataComp:this.dataComp}).addProperties({disabled:!this.dataComp.dataSource._isCreateAble});
this._toolStrip.addMember(this._btnClone);this._btnClone.hide();if(this.dataComp.dataSource._cloneSupport)this._btnClone.show();else if(null!=this.dataComp.dataSource.gridProperties){var b=isA.String(this.dataComp.dataSource.gridProperties)?isc.JSON.decode(this.dataComp.dataSource.gridProperties):this.dataComp.dataSource.gridProperties,c;for(c in b)b._cloneSupport&&this._btnClone.show()}this._toolStrip.addMember(ToolStripSeparator.create())}this._btnRel=btnRel.create({dataComp:this.dataComp}).addProperties({click:function(){this.dataComp.reload()}});
this._toolStrip.addMember(this._btnRel);this._toolStrip.addMember(ToolStripSeparator.create());this._btnXls=BtnIcon.create({title:"Export XLS",prompt:isc.i18nMessages["smartsfs.buttons.xls.prompt"],icon:"[SKIN]/custom/excel.png",dataComp:this.dataComp,click:function(){this.dataComp.exportData("xls")}});this._toolStrip.addMember(this._btnXls);this._btnCsv=BtnIcon.create({title:"Export CSV",prompt:isc.i18nMessages["smartsfs.buttons.csv.prompt"],icon:"[SKIN]/custom/csv.png",dataComp:this.dataComp,click:function(){this.dataComp.exportData("csv")}});
this._toolStrip.addMember(this._btnCsv);this._btnCsvIn=BtnIcon.create({title:"Import CSV",prompt:isc.i18nMessages["smartsfs.buttons.csvIn.prompt"],icon:"[SKIN]/custom/csv_in.png",dataComp:this.dataComp,click:function(){this.dataComp.importData("csv")}});(App.get.config["smartsfs.csvImport.support"].toString().toBoolean()&&0!=this.dataComp.dataSource.csvImport||1==this.dataComp.dataSource.csvImport)&&this._toolStrip.addMember(this._btnCsvIn);if(void 0==this.dataComp.dataSource.hasPdfReport||1==this.dataComp.dataSource.hasPdfReport)this._btnPdf=
BtnIcon.create({title:"PDF",prompt:isc.i18nMessages["smartsfs.buttons.pdf.prompt"],icon:"[SKIN]/custom/pdf.png",dataComp:this.dataComp,click:function(){this.dataComp.printPdf()}}),this._toolStrip.addMember(this._btnPdf);this._opers=[];if(0<this.dataComp.dataSource.operations.length){this.dataComp.dataSource.operations=this.dataComp.dataSource.operations.sortByProperty("position",!0);for(b=0;b<this.dataComp.dataSource.operations.length;b++)c=this.dataComp.dataSource.operations[b],"GRID"==c.placeOn.name&&
this.dataComp.dataSource.canPerformOperation(c.id)&&(c=IButton.create({prompt:c.prompt,title:c.title,autoFit:!0,snapToGrid:!0,showButtonTitle:!0,showClippedTitleOnHover:!0,icon:c.icon,dataComp:this.dataComp,_canPerform:c.canPerform||function(){return this.dataComp.dataSource.canPerformOperation(this._operationId)},_operationId:c.id,click:function(){this.dataComp.dataSource.performCustomOperation(this._operationId,this.dataComp,this.dataComp.grid.getSelectedRecord())}}),this._opers.push(c));0<this._opers.length&&
(this._operStack=isc.ToolStrip.create({maxSize:0,dataComp:this.dataComp,_handleSize:function(a){for(var b=0,c=(100/this.members.length).toString().split(".")[0]+"%",e=0;e<this.members.length;e++)var g=this.members[e],b=b+g.getVisibleWidth();1==a&&(this.maxSize=b);if(b>this.dataComp.getVisibleWidth())for(e=0;e<this.members.length;e++)g=this.members[e],g.setWidth(c),g.setAutoFit(!1);else if(this.maxSize<this.dataComp.getVisibleWidth())for(e=0;e<this.members.length;e++)g=this.members[e],g.setWidth(g.defaultWidth),
g.setAutoFit(!0)}}),this._operStack.addMembers(this._opers),this.addMember(this._operStack),this._operStack.observe(a,"resized","observer._handleSize()"),this._operStack.delayCall("_handleSize",[!0]))}isc.Browser.isHandset?(this._btnUserSetting=btnUserSetting.create({dataComp:this.dataComp}),this._toolStrip.addMember(isc.LayoutSpacer.create({defaultWidth:"100%"})),this._toolStrip.addMember(this._btnUserSetting),App.get.config["smartsfs.userSetting.handset.supported"].toString().toBoolean()||this._btnUserSetting.hide()):
(this._btnUserSetting=btnUserSetting.create({dataComp:this.dataComp}),this._toolStrip.addMember(isc.LayoutSpacer.create({defaultWidth:"100%"})),this._toolStrip.addMember(this._btnUserSetting),App.get.config["smartsfs.userSetting.supported"].toString().toBoolean()||this._btnUserSetting.hide());this.addMember(this._toolStrip);isc.Browser.isHandset?App.get.config["smartsfs.userSetting.handset.supported"].toString().toBoolean()&&(this.observe(this.dataComp,"resized","observer._handleSize()"),this.delayCall("_handleSize")):
App.get.config["smartsfs.userSetting.supported"].toString().toBoolean()&&(this.observe(this.dataComp,"resized","observer._handleSize()"),this.delayCall("_handleSize"))}}});
isc.ClassFactory.defineClass("listGridDialog","Window").addProperties({width:"50%",isModal:!0,showModalMask:!0,autoCenter:!0,autoDraw:!0,autoSize:!0,canDragResize:!0,showFooter:!0,showMinimizeButton:!1,canDragReposition:!0,canDragResize:!0,dataSource:"",selectionAppearance:"checkbox",_reqProfile:{},brefField:null,brefValue:null,_resData:function(a){},keyDown:function(){var a=isc.EventHandler.getKey(),b;if("Q"==a&&isc.EventHandler.ctrlKeyDown()||"Escape"==a)this.cancel(),b=!1;if("A"==a&&isc.EventHandler.ctrlKeyDown()||
"f2"==a)this.accept(),b=!1;return b},getCriteria:function(){var a=this.grid.getFilterEditorCriteria();if(this._reqProfile&&Object.getOwnPropertyNames(this._reqProfile).length){var b="AdvancedCriteria"==this._reqProfile._constructor?this._reqProfile:this.dataSource.convertDataSourceCriteria(this._reqProfile,"exactCase"),c=!0;if(a.hasOwnProperty("criteria"))for(var d=0;d<a.criteria.length;d++)if(a.criteria[d].fieldName==this.brefField){c=!1;break}c&&(a&&"and"==a.operator?a.criteria.push(b.criteria[0]):
(c={},a&&(c={operator:a.operator,criteria:a.criteria}),a={operator:"and",cireria:[b.citeria[0],c]}))}return a},doFilter:function(){this.grid.filterData(this.getCriteria())},cancel:function(){this.close();return this._resData(null)},accept:function(a){var b=this,c=this.grid.getSelectedRecords();a=function(a){b.brefValue||b.close();if(a)return b.brefValue&&b.close(),b._resData(c)};if(0<c.length)if(null!=b.brefField&&"single"!=b.selectionType){for(var d,f=0;f<c.length&&!(d=c[f][b.brefField]);f++);d?
isc.ask(isc.i18nMessages["dialog.listgrid.accept"].messageArgs(this.title,b.brefField,d),a):a(!0)}else a(!0);else a(!1)},showFilter:function(a){"Disabled"==a?this.grid.setProperty("showFilterEditor",!1):this.grid.setProperty("showFilterEditor",!0)},initWidget:function(){this.Super("initWidget",arguments);var a=this;if(this.dataSource){this.advFilter=isc.FilterBuilder.create({dataSource:this.dataSource});this.advFilter.hide();this.addMember(this.advFilter);this.layout=isc.VLayout.create({height:"100%",
width:"100%",managePercentBreadth:!0,minMemberSize:175});this.grid=isc.ListGrid.create({height:"100%",width:"100%",autoFitWidthApproach:"both",autoFitFieldWidths:!0,alternateRecordStyles:!0,showFilterEditor:!1,allowFilterExpressions:!0,filterEditorSubmit:function(b){a.doFilter();return!1},autoFetchData:!1,canEdit:!1,dataSource:this.dataSource,selectionAppearance:a.selectionAppearance,selectionType:a.selectionType,recordDoubleClick:function(){"single"==a.selectionType&&a.accept()},_parentComp:a});
"simple"==this.selectionType&&(this.grid.setProperty("selectionAppearance","rowStyle"),this.grid.setProperty("selectionType",this.selectionType));this.toolbar=isc.ToolStrip.create({height:30,dataComp:a,initWidget:function(){this.Super("initWidget",arguments);this._btnCancel=btnCancel.create({dataComp:this.dataComp});this.addMember(this._btnCancel);this._btnAccept=btnAccept.create({dataComp:this.dataComp});this.addMember(this._btnAccept);this._btnAccept.setDisabled(!1);this._showFilter=btnShowFilter.create({dataComp:this.dataComp});
this.addMember(this._showFilter)}});if(void 0!=a.dataSource.customProfile&&null!=a.dataSource.customProfile){var b={},b=isA.Function(a.dataSource.customProfile)?a.dataSource.customProfile(a):a.dataSource.customProfile,b="AdvancedCriteria"==b._constructor?b:a.dataSource.convertDataSourceCriteria(b,"exactCase");a._reqProfile&&Object.getOwnPropertyNames(a._reqProfile).length?a._reqProfile=DataSource.combineCriteria(a._reqProfile,b):a._reqProfile=b}this.layout.addMember(a.toolbar);this.layout.addMember(a.grid);
this.grid.fetchData(a._reqProfile,function(){a.grid.focus()});this.addItem(a.layout)}}});
