--20160127 #16168
alter table SC_CONFIG add(admin_property number(1) default 1 not null);
--20160309 valueMap na 1000
alter table SC_DSFIELD modify(value_map varchar2(1000));
--20160425 SC_HOTNEWS
ALTER TABLE SC_HOTNEWS 
RENAME COLUMN MESSAGE_TEXT TO MESSAGE_TEXTX
/
ALTER TABLE SC_HOTNEWS 
 ADD (
  MESSAGE_TEXT CLOB
 )
/
update SC_HOTNEWS set MESSAGE_TEXT = MESSAGE_TEXTX;
commit;
ALTER TABLE SC_HOTNEWS 
 DROP COLUMN   MESSAGE_TEXTX
/