Select 'new SmartSource(ID:"' || ID || '",addDataURL:"' || ADD_DATAURL || '",dataField:"' || DATA_FIELD || '",dataFormat:"' || DATA_FORMAT
      ||'",dataURL:"'||DATAURL||'",descriptionField:"'||DESCRIPTION_FIELD||'",disableQueuing:'||case DISABLE_QUEUING when 1 then 'true' when 0 then 'false' else 'null' end
      ||',fetchDataURL:"'||FETCH_DATAURL||'",iconField:"'||ICON_FIELD||'",infoField:"'||INFO_FIELD||'",jsonPrefix:"'||JSON_PREFIX
      ||'",jsonRecordXPath:"'||JSON_RECORDXPATH||'",jsonSuffix:"'||JSON_SUFFIX||'",pluralTitle:"'||PLURAL_TITLE||'",removeDataURL:"'||REMOVE_DATAURL
      ||'",requiresRole:"'||REQUIRES_ROLE||'",title:"'||TITLE||'",titleField:"'||TITLE_FIELD||'",updateDataurl:"'|| UPDATE_DATAURL
      ||'",canEdit:'||case CAN_EDIT when 1 then 'true' when 0 then 'false' else 'null' end||',canSave:'||case CAN_SAVE when 1 then 'true' when 0 then 'false' else 'null' end
      ||',editRequiresRole:"'||EDIT_REQUIRES_ROLE||'",saveRequiresRole:"'||SAVE_REQUIRES_ROLE||'",detailFormDS:"'||DETAIL_FORMDS
      ||'",inheritsFrom:"'|| INHERITS_FROM||'",detailFormUri:"'||DETAIL_FORM_URI||'",deleteRequiresRole:"'|| DELETE_REQUIRES_ROLE
      ||'",gridProperties:"'||GRID_PROPERTIES||'").save(flush:true)' as line
From   sc_datasource;


SELECT 'new SmartSourceField(name:"'||NAME||'",autoGenerated:'||case AUTO_GENERATED  when 1 then 'true' when 0 then 'false' else 'null' end
   ||',canEdit:'||case CAN_EDIT  when 1 then 'true' when 0 then 'false' else 'null' end||',canFilter:'||case CAN_FILTER when 1 then 'true' when 0 then 'false' else 'null' end
   ||',canSave:'||case CAN_SAVE  when 1 then 'true' when 0 then 'false' else 'null' end||',decimalPad:'||nvl(to_char(DECIMAL_PAD),'null')
   ||',decimalPrecision:'||nvl(to_char( DECIMAL_PRECISION),'null')||',detail:'||case DETAIL  when 1 then 'true' when 0 then 'false' else 'null' end
   ||',displayField:"'|| DISPLAY_FIELD||'",dSource:SmartSource.findWhere(ID:"'||(select ID from sc_datasource where metaid=XDATASOURCE)||'"),editRequiresRole:"'
   || EDIT_REQUIRES_ROLE||'",editorType:"'|| EDITOR_TYPE||'",fieldPosition:'|| FIELD_POSITION||',foreignDisplayField:"'||FOREIGN_DISPLAY_FIELD
   ||'",foreignKey:"'|| FOREIGN_KEY||'",hidden:'||case HIDDEN when 1 then 'true' when 0 then 'false' else 'null' end||',includeFrom:"'||INCLUDE_FROM
   ||'",includeVia:"'|| INCLUDE_VIA||'",length:'||nvl(to_char( LENGTH),'null')||',primaryKey:'||case PRIMARY_KEY when 1 then 'true' when 0 then 'false' else 'null' end
   ||',propertiesOnly:'||case PROPERTIES_ONLY when 1 then 'true' when 0 then 'false' else 'null' end||',readOnlyEditorType:"'|| READ_ONLY_EDITOR_TYPE
   ||'",required:'||case REQUIRED when 1 then 'true' when 0 then 'false' else 'null' end||',rootValue:"'|| ROOT_VALUE||'",title:"'||replace(TITLE,'"','\"')
   ||'",type:"'||TYPE||'",updateRequiresRole:"'||UPDATE_REQUIRES_ROLE||'",validOperators:"'||replace(VALID_OPERATORS,'"','\"')
   ||'",validators:"'||replace(VALIDATORS,'"','\"')||'",valueXPath:"'|| VALUEXPATH||'",viewRequiresRole:"'||VIEW_REQUIRES_ROLE
   ||'",formItemProps:"'||replace(FORM_ITEM_PROPS,'"','\"')||'",optionDataSource:"'|| OPTION_DATA_SOURCE
   ||'",canFocus:'||case CAN_FOCUS when 0 then 'false' else 'true' end||',valueField:"'|| VALUE_FIELD||'",multiple:'||case MULTIPLE when 1 then 'true' when 0 then 'false' else 'null' end
   ||',multipleStorage:"'||MULTIPLE_STORAGE||'",prompt:"'||replace(PROMPT,'"','\"')||'", characterCasing:"'||CHARACTER_CASING||'",mask:"'||MASK
   ||'",valueMap:"'||replace( VALUE_MAP,'"','\"')||'").save(flush:true)' as line
FROM SC_DSFIELD where xdatasource not in(5,222,21,101,102,281,302) order by xdatasource,field_position;

SELECT 'new SmartOperation(needRefresh:'||case NEED_REFRESH when 1 then 'true' when 0 then 'false' else 'null' end
   ||',placeOn:'||case PLACE_ON when 1 then 'PlaceOnType.DETAIL' when 2 then 'PlaceOnType.GRID' else 'null' end
   ||',title:"'||replace(TITLE,'"','\"')||'",uri:"'||URI||'",useIdAsOnlyParam:'||case USE_ID_AS_ONLY_PARAM when 1 then 'true' when 0 then 'false' else 'null' end
   ||',callbackOnSuccess:"'||replace(CALLBACK_ON_SUCCESS,'"','\"')||'",callbackParam:"'||replace(CALLBACK_PARAM,'"','\"')
   ||'",dSource:SmartSource.findWhere(ID:"'||(select ID from sc_datasource where metaid=XDATASOURCE)||'"),prompt:"'||replace(PROMPT,'"','\"')
   ||'",requiresRole:"'||REQUIRES_ROLE||'",returnMsgPath:"'||RETURN_MSG_PATH||'",returnStatusPath:"'||RETURN_STATUS_PATH
   ||'",successTestValue:"'||replace(SUCCESS_TEST_VALUE,'"','\"')||'",icon:"'||ICON||'").save(flush:true)' as line
FROM SC_OPERATION;